### ISSUE TITLE
2023.5.4 Problem: 1. Two Sum

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#1]
1. Two Sum     Easy

[Link](https://leetcode.com/problems/two-sum/)

Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

You can return the answer in any order.

Example 1:

```
Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].
```
Example 2:

```
Input: nums = [3,2,4], target = 6
Output: [1,2]
```
Example 3:

```
Input: nums = [3,3], target = 6
Output: [0,1]
```

**Comment by umdreamer** [comment]
![K_HDAPX2DV54CDY{35WA0Z0](https://user-images.githubusercontent.com/15782682/236069256-fb8a7b53-7253-49a6-ba95-84764e69d053.png)

**Comment by 686xiaozhang** [comment]
![QQ截图20230504125821](https://user-images.githubusercontent.com/132082348/236115809-b42e046e-279c-4296-97cc-b9a4b0bc8425.png)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-04 150233](https://user-images.githubusercontent.com/117709686/236137137-2e67c6bb-e593-4d89-8461-2768c079ea9a.png)

**Comment by 686xiaozhang** [comment]
``class Solution {
public:
    vector<int> twoSum(vector<int>& nums, int target) {
        int i,j;
        for (int i=0;i<nums.size();i++)
        {
            for (int j=i+1;j<nums.size();j++)
            {
                if (nums[i]+nums[j]==target)
                return {i,j};
            }
        }
        return {i,j};        
    }
};

**Comment by zyhzxy99** [comment]
#include<iostream>
using namespace std;
int main() {
	int nums[] = { 4,7,9,6,5,10 };
	int n = 6;
	int target, x, y;
	int result[] = { -1,-1 };
	cout << "请输入目标target值:" << endl;
	cin >> target;
	for (x = 0; x < n - 1; x++) {
		for (y = x + 1; y < n; y++) {
			if (nums[x] + nums[y] == target) {
				result[0] = x;
				result[1] = y;
				
				cout << "[" << result[0] << "," << result[1] << "]" << endl;
			}
			else {
				cout << "无此值" << endl;
			}
		}
	}
	

	return 0;

}

**Comment by ZWJ2212061008** [comment]
![image](https://user-images.githubusercontent.com/132138380/236191020-c1adf238-520e-45c7-93c9-8264c477d7ac.png)

**Comment by huangyumei1** [comment]
![QQ图片20230504185130](https://user-images.githubusercontent.com/122475924/236191819-f1e73c89-c37f-418a-adf2-aa16b6d82ef0.png)

**Comment by foxbou** [comment]
![04193240](https://user-images.githubusercontent.com/132526020/236192144-9154a353-4f54-4763-ace4-0558df4b7e2e.png)

**Comment by naqianqpg** [comment]
![{{O6QI9A5YX2HR` Y97O76W](https://user-images.githubusercontent.com/132567187/236192620-3a1802e2-db27-4acf-9e12-d57286cde7c0.png)

**Comment by 123lrb** [comment]
![~{TM~5D_$~J65($0K5_)6UB](https://user-images.githubusercontent.com/132526491/236194303-2680aca4-aa7a-4b32-aaa7-6afd6a4f18ca.png)

**Comment by liuhuanyu6** [comment]
![屏幕截图 2023-05-04 194208](https://user-images.githubusercontent.com/132526191/236194384-d14d6f88-d5a7-43c2-9c2d-e25dc78942c6.png)

**Comment by PinkyLame** [comment]
![屏幕截图 2023-05-04 193635](https://user-images.githubusercontent.com/132571584/236194383-b7d6d789-66a0-4729-8076-04ba4a165c33.png)

**Comment by zangfushuo** [comment]
[
](https://leetcode.com/problems/two-sum/)

**Comment by tangyexi** [comment]
<img width="896" alt="屏幕截图 2023-05-04 194001" src="https://user-images.githubusercontent.com/132453549/236194696-57700cc3-43c9-4810-bc5c-8469fbca8e1b.png">

**Comment by zangfushuo** [comment]
<img width="682" alt="截屏2023-05-04 19 44 22" src="https://user-images.githubusercontent.com/132563136/236194737-60713319-af1e-429e-9b16-7602c1452f46.png">

**Comment by 198528** [comment]
<img width="876" alt="屏幕截图 2023-05-04 194614" src="https://user-images.githubusercontent.com/126148849/236194749-6e4aa413-0e9a-4aeb-89ab-1af12fdcd58b.png">

**Comment by zyhzxy99** [comment]
![D W{7RB(LOIM5HD7SR8ADN8](https://user-images.githubusercontent.com/132050929/236195081-bf852ebe-1b89-414a-9a39-2a434826a663.png)

**Comment by gusuning** [comment]
<img width="876" alt="屏幕截图 2023-05-04 194614" src="https://user-images.githubusercontent.com/126148849/236195134-25c2c38c-3f3f-498b-bed3-7a10d4209302.png">

**Comment by liu-si-han** [comment]
<img width="413" alt="image" src="https://user-images.githubusercontent.com/132453391/236194977-c7d80b0b-32c5-40e2-8451-13d7898c7d35.png">

**Comment by mafanjia** [comment]
![截屏1](https://user-images.githubusercontent.com/132454776/236195480-b3b93179-dd60-43b3-8604-7c0358a07b96.png)

**Comment by daowuwu** [comment]
![M~8RVS9R33@I07CC838P~E5](https://user-images.githubusercontent.com/132571490/236195975-cf4472e8-0bbc-4fbd-8a68-7d7f4a10ae9a.png)

**Comment by zhjingyan** [comment]
![屏幕截图 2023-05-04 194032](https://user-images.githubusercontent.com/132195009/236196306-7fb225af-ec2c-4847-b238-557fdaea065d.png)

**Comment by xiaolu2002** [comment]
[](url)

**Comment by zyhzxy99** [comment]
![0E10EDDCED076A2FE69E18D0B6690842](https://user-images.githubusercontent.com/132050929/236196701-3a254b58-f992-4c8e-8bee-fe7a891bef32.jpg)

**Comment by cuixiao02** [comment]
<img width="524" alt="截屏2023-05-04 19 17 04" src="https://user-images.githubusercontent.com/132454083/236197197-4d75a863-4d3b-4a72-9adb-decf4c68e73e.png">

**Comment by xiaolu2002** [comment]
![image](https://user-images.githubusercontent.com/132567090/236197831-20b29fa1-47ac-49b1-98d2-02ba2987e184.png)

**Comment by htywan** [comment]
![1](https://user-images.githubusercontent.com/132428178/236201187-1edd62e9-9653-4bf3-adb1-1c50270b7616.png)

**Comment by sjh397** [comment]
![屏幕截图 2023-05-04 195923](https://user-images.githubusercontent.com/132568283/236201671-a624ddf5-92a1-484f-b1da-c2f28e4ab60a.png)

**Comment by yeyuxq** [comment]
![}Z1O6T7(OD$FP2MD787} QR](https://user-images.githubusercontent.com/128273789/236202926-07174fa3-e6c2-46d3-a9af-089ac6e01a80.png)

**Comment by 686xiaozhang** [comment]
![Uploading QQ截图20230504204317.png…]()

**Comment by 686xiaozhang** [comment]
![QQ截图20230504204317](https://user-images.githubusercontent.com/132082348/236209360-1fe4288e-1191-4c32-837c-95356ec19d36.png)

**Comment by bedauern** [comment]
<img width="931" alt="Snipaste_2023-05-04_20-49-08" src="https://user-images.githubusercontent.com/132483498/236210362-2e2f2392-ca06-47b3-b691-c9a32ac12fa6.png">

**Comment by promisewith7** [comment]
![O)GTF)K@NCZKZMQ9 XM9 C6](https://user-images.githubusercontent.com/132559311/236211249-1a2714d2-52cd-4cc1-a854-e419ca4d7bc3.png)

**Comment by 1125766961** [comment]
![image](https://user-images.githubusercontent.com/132560784/236211278-b9eb78f9-9730-419e-af44-e2bfb3b4b139.png)

**Comment by qby962464** [comment]
![Snipaste_2023-05-04_19-00-03](https://user-images.githubusercontent.com/132563315/236211815-77fd7046-b5f9-46e9-8489-1dde1f807bdf.png)

**Comment by zxm-1235** [comment]
![image](https://user-images.githubusercontent.com/132538992/236212030-07be2126-04ae-466a-b743-84e3b2e8d08a.png)

**Comment by xkqwww** [comment]
![xk](https://user-images.githubusercontent.com/132559761/236212298-61cdcd1b-6c5a-453d-b116-4d26aa1c6e3a.png)

**Comment by FXL1006** [comment]
<img width="588" alt="屏幕截图 2023-05-04 205537" src="https://user-images.githubusercontent.com/132453630/236212489-046ce7cc-1eea-4058-bf03-dde0214c0fe1.png">

**Comment by wangshiqi7** [comment]
![Uploading A08F0072-80E2-4756-9121-A9AAA3E9DCE0.png…]()

**Comment by syr2212061031** [comment]
![WWNCC9O66FFB0FQ1BEK{E{Q](https://user-images.githubusercontent.com/132579828/236216077-c0fad733-fd06-419c-a3df-1f4e1e28254c.png)

**Comment by 12baoxingyu-6** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/132574617/236217132-b876fadf-2c20-4dc3-ac93-fb1cb4893b86.png">

**Comment by 24zlx** [comment]
![无标题](https://user-images.githubusercontent.com/132560099/236218586-d6d44270-ae4d-44e5-9e81-2a5ac156fa4f.png)

**Comment by shylieisme** [comment]
![RL3X9R{%_ {IY%608FZST5I](https://user-images.githubusercontent.com/132582721/236224054-c9d52ede-a9d9-42ac-87f5-aaf4cd04ef4e.png)

**Comment by wangshiqi7** [comment]
![Uploading 32C1B55E-27C9-4017-A404-25C35A6617CC.jpeg…]()

**Comment by liuhuanyu6** [comment]
![image](https://user-images.githubusercontent.com/132526191/236445617-f07586f1-bce3-4a99-8168-800be0a3e781.png)

**Comment by wangshiqi7** [comment]
![P{Y8A(1HXQQ052X_0HZBI3C](https://user-images.githubusercontent.com/132578339/236464932-e153907b-1369-49d7-896d-b8b8bb3fe835.png)

**Comment by zyhzxy99** [comment]
![DP)RZF8_T2` 5FE57~VVZ6K](https://user-images.githubusercontent.com/132050929/236507017-71e88647-014c-45dd-af8b-a8fd3baa9dcc.png)

**Comment by cuixiao02** [comment]
<img width="680" alt="截屏2023-05-09 19 53 35" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/eba0143e-8389-4a5d-bcdb-9b98488fa509">
