### ISSUE TITLE
2023.5.11 Problem: 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#10]
26. Remove Duplicates from Sorted Array

[Problem Link](https://leetcode.cn/problems/remove-duplicates-from-sorted-array/)

Given an integer array nums sorted in non-decreasing order, remove the duplicates [in-place](https://en.wikipedia.org/wiki/In-place_algorithm) such that each unique element appears only once. The relative order of the elements should be kept the same. Then return the number of unique elements in nums.

Consider the number of unique elements of nums to be k, to get accepted, you need to do the following things:

Change the array nums such that the first k elements of nums contain the unique elements in the order they were present in nums initially. The remaining elements of nums are not important as well as the size of nums.
Return k.
Custom Judge:

The judge will test your solution with the following code:

```
int[] nums = [...]; // Input array
int[] expectedNums = [...]; // The expected answer with correct length

int k = removeDuplicates(nums); // Calls your implementation

assert k == expectedNums.length;
for (int i = 0; i < k; i++) {
    assert nums[i] == expectedNums[i];
}
```
If all assertions pass, then your solution will be accepted.

 

Example 1:

```
Input: nums = [1,1,2]
Output: 2, nums = [1,2,_]
Explanation: Your function should return k = 2, with the first two elements of nums being 1 and 2 respectively.
It does not matter what you leave beyond the returned k (hence they are underscores).
```
Example 2:

```
Input: nums = [0,0,1,1,1,2,2,3,3,4]
Output: 5, nums = [0,1,2,3,4,_,_,_,_,_]
Explanation: Your function should return k = 5, with the first five elements of nums being 0, 1, 2, 3, and 4 respectively.
It does not matter what you leave beyond the returned k (hence they are underscores).
``` 

Constraints:

* 1 <= nums.length <= 3 * 104
* -100 <= nums[i] <= 100
* nums is sorted in non-decreasing order.

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/f3ea79dd-a800-489c-8e58-81a0674e6324)

**Comment by FXL1006** [comment]
<img width="755" alt="屏幕截图 2023-05-11 143445" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/be88f4b3-d8f8-47bd-9167-441eb0ecf50d">

**Comment by foxbou** [comment]
<img width="945" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/ce7f3db2-c3e3-4eff-84a1-dc09fc72d15e">

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/50537a68-388f-4be9-996a-1a7b57fca76a)

**Comment by tangyexi** [comment]
<img width="835" alt="屏幕截图 2023-05-11 185222" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/f546a5d2-7e5f-43af-95cc-cad08f169cd0">

**Comment by 686xiaozhang** [comment]
![QQ截图20230511162546](https://github.com/umdreamer/leetcodeproblems/assets/132082348/86177314-37b8-40be-9dde-4015933ea29e)

**Comment by zyhzxy99** [comment]
![SNTK@%~S4C@T`~JYZK)5B I](https://github.com/umdreamer/leetcodeproblems/assets/132050929/3ab44f6b-b5ed-46b3-8e0e-a4708c7ea7ca)

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/04ed089d-ea59-4f55-8cc5-cf862844418a)

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/4069f326-4344-45cb-b305-8004966b6a2f)

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/2fd0c4a1-2bf9-4be8-9066-9c3ce8bc2922)

**Comment by daowuwu** [comment]
![EIR}(64JLCOU6@KN1DQ7F54](https://github.com/umdreamer/leetcodeproblems/assets/132571490/3a6f4261-9e92-47c3-b643-0545588eeead)

**Comment by mafanjia** [comment]
![截屏1](https://github.com/umdreamer/leetcodeproblems/assets/132454776/f39d58c1-4c99-465f-b7bd-ae446dd7182c)

**Comment by cuixiao02** [comment]
<img width="651" alt="截屏2023-05-11 19 56 35" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/09393d52-508c-4d49-9601-71a4ab615231">

**Comment by liu-si-han** [comment]
<img width="806" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/062f8b53-9368-4807-b5f4-e5b48ee17a71">

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/83e257f3-c71a-4fa4-a084-43cc680ffc9b)

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/023b9638-c663-4c5b-a99c-226d4172c8f1)

**Comment by xkqwww** [comment]
![5](https://github.com/umdreamer/leetcodeproblems/assets/132559761/e0016f72-74c0-4a98-bd26-d1c04fa9a908)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-11 200126](https://github.com/umdreamer/leetcodeproblems/assets/117709686/6c26c349-1d84-4221-900f-eef0176b1e2e)

**Comment by huangyumei1** [comment]
![QQ图片20230511201129](https://github.com/umdreamer/leetcodeproblems/assets/122475924/068e23db-7463-4f05-bb01-4490cd4d071e)

**Comment by 123lrb** [comment]
![8Z71Y5LB`B)8X@ B66F`ZU2](https://github.com/umdreamer/leetcodeproblems/assets/132526491/b127a3fe-c36b-44f2-b7fe-fd5a2e54bfba)

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/4b14340c-5aa5-4970-9820-122efbf4b7da)

**Comment by bedauern** [comment]
<img width="802" alt="Snipaste_2023-05-11_20-53-45" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/66600284-4ff7-4d8e-8899-a0d7d15337a7">

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/6210b2ca-6dee-4fa1-8beb-8b0525df051e)

**Comment by gusuning** [comment]
<img width="899" alt="屏幕截图 2023-05-10 192718" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/4ac578fb-b2d6-425c-a4b2-b79836f64ded">

**Comment by 12baoxingyu-6** [comment]
<img width="804" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/4309659f-bfe0-4453-9a08-39686f44042e">

**Comment by htywan** [comment]
![8](https://github.com/umdreamer/leetcodeproblems/assets/132428178/0fcb4ff4-7949-4a65-ba13-31a700d13ca7)

**Comment by 24zlx** [comment]
![联想截图_20230511211256](https://github.com/umdreamer/leetcodeproblems/assets/132560099/4e9b7266-8249-474c-88f2-5c4c8cac56fd)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-11 21 26 15" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/1bf47e90-3af1-40c2-a4c5-0f7776e0cd4b">
ss

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-11 21 26 15" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/c15ae157-80fe-4674-bcc9-a66a9ed47df2">

**Comment by naqianqpg** [comment]
![EZYOK0W%LPB4VT`V @X YOC](https://github.com/umdreamer/leetcodeproblems/assets/132567187/085bbfdd-1a5c-4f2b-a95a-8ee419fe81cd)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/02d8e2b8-085e-4255-bc27-53d297a06a1f)

**Comment by zangfushuo** [comment]
<img width="622" alt="截屏2023-05-11 22 38 32" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/daf4c30f-8154-4b3c-bd3e-f0415e48b08d">

**Comment by syr2212061031** [comment]
![(4Y_VGQPAB21NJ9CN3DM LW](https://github.com/umdreamer/leetcodeproblems/assets/132579828/84ea5fc6-263d-438c-9552-684db375f516)

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/ca2d0d72-74fa-48d6-8bef-0ca21179a0d9)

**Comment by shylieisme** [comment]
![4`H}46 4CE6IR0(SC(5}UKC](https://github.com/umdreamer/leetcodeproblems/assets/132582721/80875a57-118b-4531-b343-d9a6b61958bf)
