### ISSUE TITLE
2023.5.12 Problem: 27. Remove Element

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#11]
27. Remove Element
[Problem Link](https://leetcode.cn/problems/remove-element/)

Given an integer array nums and an integer val, remove all occurrences of val in nums [in-place](https://en.wikipedia.org/wiki/In-place_algorithm). The order of the elements may be changed. Then return the number of elements in nums which are not equal to val.

Consider the number of elements in nums which are not equal to val be k, to get accepted, you need to do the following things:

Change the array nums such that the first k elements of nums contain the elements which are not equal to val. The remaining elements of nums are not important as well as the size of nums.
Return k.
Custom Judge:

The judge will test your solution with the following code:

```
int[] nums = [...]; // Input array
int val = ...; // Value to remove
int[] expectedNums = [...]; // The expected answer with correct length.
                            // It is sorted with no values equaling val.

int k = removeElement(nums, val); // Calls your implementation

assert k == expectedNums.length;
sort(nums, 0, k); // Sort the first k elements of nums
for (int i = 0; i < actualLength; i++) {
    assert nums[i] == expectedNums[i];
}

```
If all assertions pass, then your solution will be accepted.

 

Example 1:

```
Input: nums = [3,2,2,3], val = 3
Output: 2, nums = [2,2,_,_]
Explanation: Your function should return k = 2, with the first two elements of nums being 2.
It does not matter what you leave beyond the returned k (hence they are underscores).
```
Example 2:

```
Input: nums = [0,1,2,2,3,0,4,2], val = 2
Output: 5, nums = [0,1,4,0,3,_,_,_]
Explanation: Your function should return k = 5, with the first five elements of nums containing 0, 0, 1, 3, and 4.
Note that the five elements can be returned in any order.
It does not matter what you leave beyond the returned k (hence they are underscores).
```

Constraints:

* `0 <= nums.length <= 100`
* `0 <= nums[i] <= 50`
* `0 <= val <= 100`

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/66dd7e53-9d2f-40d2-965f-dcee5ada52ca)

**Comment by huangyumei1** [comment]
![QQ图片20230512184705](https://github.com/umdreamer/leetcodeproblems/assets/122475924/71ce972f-5ee8-4e94-bdc8-28fb2399ac24)

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/b95c4e52-247a-49a1-b3a0-756403222758)

**Comment by foxbou** [comment]
<img width="959" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/b3019cca-77a8-47e5-9881-800c363004e3">

**Comment by liu-si-han** [comment]
<img width="803" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/c851ed8a-2e10-43ca-a9ae-9de9f7e5fcb2">

**Comment by mafanjia** [comment]
![截屏2](https://github.com/umdreamer/leetcodeproblems/assets/132454776/989dda1d-6750-4a54-861a-015ff083a3a5)

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/b57c06ca-1306-4119-b080-374e89810cd0)

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/d1fe6966-bf56-4d7b-9e82-656ef45bcd19)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/2f58429c-bdad-4f60-93af-cc4309d6b29f)

**Comment by cuixiao02** [comment]
<img width="639" alt="截屏2023-05-12 20 02 50" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/6d490489-f46f-4c5e-852c-66e6d2b9b91a">

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/01e953c5-b898-4387-94df-7f01c8af4325)

**Comment by 123lrb** [comment]
![KV_)_ X@QLMUEZO%JTJ$Z20](https://github.com/umdreamer/leetcodeproblems/assets/132526491/638526d2-4b8e-485d-9ad9-f48599f810cf)

**Comment by tangyexi** [comment]
<img width="892" alt="屏幕截图 2023-05-12 204903" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/38c59079-dcc7-40fd-91e2-0f479e999381">

**Comment by gusuning** [comment]
<img width="943" alt="屏幕截图 2023-05-12 205229" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/f3703f56-4c5d-4d7c-be4f-ac8b24c6637b">

**Comment by syr2212061031** [comment]
![0)Q0IME33OXFEA_~3N9ZW}G](https://github.com/umdreamer/leetcodeproblems/assets/132579828/f4ccb9be-fcdd-4fca-a4b6-d3c9d5b431e3)

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/2b6c9787-6917-49d6-aa61-d068200862d7)

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/636ddaab-64d3-48f0-bac6-4ef3d38a7c48)

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/4a949281-eecd-42d5-9d72-baae3568ab0c)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-12 210539](https://github.com/umdreamer/leetcodeproblems/assets/117709686/68cbb63b-54fa-42d3-8e63-afa1fb5e9a74)

**Comment by FXL1006** [comment]
<img width="743" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/c7a7c7b1-eabd-475e-a622-683f54b4c2dc">

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/219ed0e8-04e2-47c7-aa68-ac0485c8ea4a)

**Comment by htywan** [comment]
![Uploading 6.png…]()

**Comment by htywan** [comment]
![6](https://github.com/umdreamer/leetcodeproblems/assets/132428178/acf8bcf5-211d-4956-b7e2-df04fc32b2e6)

**Comment by 24zlx** [comment]
![联想截图_20230512214323](https://github.com/umdreamer/leetcodeproblems/assets/132560099/021ed2aa-697a-4290-88e5-bc0e64f9d2b9)

**Comment by 686xiaozhang** [comment]
![QQ截图20230512214921](https://github.com/umdreamer/leetcodeproblems/assets/132082348/ccd41ecd-2d04-4a02-97ca-f03321c6971e)

**Comment by naqianqpg** [comment]
![B74ELZLFJBGSIX@)P` GSYN](https://github.com/umdreamer/leetcodeproblems/assets/132567187/ee159117-0680-4589-aab1-0970d84c5db9)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/d5f8df14-7123-4f9a-a5a7-cae61e7e2a76)

**Comment by zyhzxy99** [comment]
![W7@8OW7@~ R}5@9620W(ZH2](https://github.com/umdreamer/leetcodeproblems/assets/132050929/7ed576da-dba8-47ce-859d-d81df46311fa)

**Comment by 12baoxingyu-6** [comment]
<img width="771" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/94d700de-39f2-4a3f-bb41-4f729b096aed">

**Comment by bedauern** [comment]
<img width="859" alt="Snipaste_2023-05-12_23-00-27" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/08835fe1-b97c-41a7-b0bc-06ac99430e95">

**Comment by shylieisme** [comment]
![~YNDZA) JGPFU1CKO{4VNCY](https://github.com/umdreamer/leetcodeproblems/assets/132582721/6f1d9c01-86ce-453f-af7d-e75772485a9a)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-11 21 26 15" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/24c17ab5-5d39-4418-97df-3e2ce7d996fc">
