### ISSUE TITLE
2023.5.13 Problem: 35. Search Insert Position

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#12]
35. Search Insert Position
[Problem Link](https://leetcode.cn/problems/search-insert-position/)

Given a sorted array of distinct integers and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order.

You must write an algorithm with O(log n) runtime complexity.

 

Example 1:
```
Input: nums = [1,3,5,6], target = 5
Output: 2
```
Example 2:
```
Input: nums = [1,3,5,6], target = 2
Output: 1
```
Example 3:
```
Input: nums = [1,3,5,6], target = 7
Output: 4
``` 

Constraints:

* 1 <= nums.length <= 104
* -104 <= nums[i] <= 104
* nums contains distinct values sorted in ascending order.
* -104 <= target <= 104

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/c55790e4-8fe2-4168-9722-43468a9092e1)

**Comment by 123lrb** [comment]
![)RF8}J A8W9TGQV4K`DOQ M](https://github.com/umdreamer/leetcodeproblems/assets/132526491/43cb5ffb-e986-4a4d-98d1-1ec96407fb9a)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-13 115608](https://github.com/umdreamer/leetcodeproblems/assets/117709686/bfbf9fa1-6186-4f56-8dac-ed5ffd1af6b4)

**Comment by syr2212061031** [comment]
![LZ(YL32{$MQUD % 4A`VZ9U](https://github.com/umdreamer/leetcodeproblems/assets/132579828/77b6f728-0320-4c7c-8b4c-ad9aba4928ed)

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/7adf3435-75b7-43bb-9d02-ca0e4ccc37b4)

**Comment by shylieisme** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132582721/0d5412a4-11a6-42ed-beac-030b9e4d6a4b)

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/ee4d5246-158c-4ff3-bb2d-fccb352de35a)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/5cf4dd06-797d-4d8e-bd34-4323704088cf)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/7f58a39d-97b9-4ac5-b4e7-4fa52d525418)

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/1e0692b6-b01a-4ebb-92f0-8cd489faa21f)

**Comment by huangyumei1** [comment]
![QQ图片20230513192803](https://github.com/umdreamer/leetcodeproblems/assets/122475924/2584a55d-e86d-4a97-b43b-c4511f7f3e16)

**Comment by mafanjia** [comment]
![截屏3](https://github.com/umdreamer/leetcodeproblems/assets/132454776/1fc7ff50-a917-49dd-8e2c-d6b4540f9e93)

**Comment by 1125766961** [comment]
![QR``(` E%YAAPHA26K1BMTY](https://github.com/umdreamer/leetcodeproblems/assets/132560784/a9d7b020-09f4-4d04-8c69-e444a3aeb835)

**Comment by daowuwu** [comment]
![SP@45Q{44V58V9%05YD_AXM](https://github.com/umdreamer/leetcodeproblems/assets/132571490/51cb6277-1e0a-467b-87c9-8e8fd82ba5ff)

**Comment by zyhzxy99** [comment]
![XJZ@8 JTV50V}C4@UFP{2ZH](https://github.com/umdreamer/leetcodeproblems/assets/132050929/98224c8d-aed4-43df-aa5d-9db303836dff)

**Comment by liu-si-han** [comment]
<img width="836" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/98378f06-dc69-4855-9228-17bc202228a4">

**Comment by tangyexi** [comment]
<img width="837" alt="屏幕截图 2023-05-13 194931" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/bffe3067-b04e-400c-913c-f941df44d414">

**Comment by 24zlx** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132560099/7cb49d8e-83dd-422f-9f76-8a081a26bd03)

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/f2dd022a-5284-41b7-8daa-e5c5b47e1108)

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/2fe713a7-9ace-4fac-8665-a1a40f30b4f4)

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/b8745067-11bb-4476-be01-795cb83ab3f6)

**Comment by cuixiao02** [comment]
<img width="649" alt="截屏2023-05-13 20 31 45" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/6e190c12-0612-4caf-87fc-6958f25dd4e8">

**Comment by 686xiaozhang** [comment]
![QQ截图20230513210616](https://github.com/umdreamer/leetcodeproblems/assets/132082348/f6c6848c-58ee-48f7-9827-63981fdfac28)

**Comment by htywan** [comment]
![1](https://github.com/umdreamer/leetcodeproblems/assets/132428178/5e453fa6-51ed-4d56-bfcb-c6c499bf3caf)

**Comment by 12baoxingyu-6** [comment]
<img width="814" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/6bd3fb17-0fcc-4286-a2d1-c64e8808300a">

**Comment by naqianqpg** [comment]
![@ %VYSY$)~L9@880){{RX2R](https://github.com/umdreamer/leetcodeproblems/assets/132567187/2c41ebc3-0ec6-45b7-92b4-b80c30dce628)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-13 21 23 53" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/43d48714-28fa-4784-8c61-a086bca56c85">

**Comment by gusuning** [comment]
<img width="31" alt="屏幕截图 2023-05-13 215536" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/6c9987d4-f58b-4128-9181-fb2f37589bee">

**Comment by gusuning** [comment]
<img width="826" alt="屏幕截图 2023-05-13 215542" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/3318967c-55bb-4859-adc3-2bd75b103b10">

**Comment by liuhuanyu6** [comment]
https://github.com/umdreamer/leetcodeproblems/issues/1

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/00eb31b6-9fd4-4072-8437-ea28667945fa)

**Comment by foxbou** [comment]
<img width="1075" alt="屏幕截图 2023-05-09 175609" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/b0c08459-647f-4dcb-b1ed-07157e44f6cb">

**Comment by foxbou** [comment]
<img width="936" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/5627d711-d49a-4471-a62e-8e6a5b14ff6a">

**Comment by FXL1006** [comment]
<img width="881" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/6afafd33-526c-4335-9004-8a519b6ee2fc">

**Comment by bedauern** [comment]
<img width="825" alt="Snipaste_2023-05-13_22-20-59" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/4a658e2f-38f2-4015-9e9f-73bd8c3b3a25">
