### ISSUE TITLE
2023.5.15 Problem: 58. Length of Last Word

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#13]
58. Length of Last Word
[Problem Link](https://leetcode.cn/problems/length-of-last-word/)

Given a string s consisting of words and spaces, return the length of the last word in the string.

A word is a maximal substring consisting of non-space characters only.

Example 1:
```
Input: s = "Hello World"
Output: 5
Explanation: The last word is "World" with length 5.
```
Example 2:
```
Input: s = "   fly me   to   the moon  "
Output: 4
Explanation: The last word is "moon" with length 4.
```
Example 3:
```
Input: s = "luffy is still joyboy"
Output: 6
Explanation: The last word is "joyboy" with length 6.
``` 

Constraints:

* `1 <= s.length <= 104`
* `s consists of only English letters and spaces ' '.`
* `There will be at least one word in s.`

**Comment by huangyumei1** [comment]
![QQ图片20230515123703](https://github.com/umdreamer/leetcodeproblems/assets/122475924/ed0570d7-9893-4054-b50b-4708a5920c89)

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/cf0cefd7-434c-4b4a-8711-be7287bc42e7)

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/32cf09ec-3a14-4984-b955-1dc71d5612db)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/2f92b777-f2e1-4325-b36d-c5f659b4b854)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-15 145104](https://github.com/umdreamer/leetcodeproblems/assets/117709686/48c15444-5577-451f-bb58-ba2fdb9f2af3)

**Comment by zangfushuo** [comment]
<img width="652" alt="截屏2023-05-15 15 18 31" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/8852d1fc-3eca-48fd-b826-c7f6bc72ae41">

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/286ed891-2238-466d-9849-05d91ba867d0)

**Comment by tangyexi** [comment]
<img width="901" alt="屏幕截图 2023-05-15 174001" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/afba75e8-d639-4b99-9b99-7ec38df7dea4">

**Comment by foxbou** [comment]
<img width="1035" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/a194c0d3-3e74-4369-845f-a867c89ee74a">

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/9c3b41b9-b9ac-442e-b1a6-ab43f366d564)

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/8c2bca00-0cec-41d7-a96f-29c6b4cdc4f1)

**Comment by cuixiao02** [comment]
<img width="645" alt="截屏2023-05-15 18 56 32" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/510402c1-7293-497d-874c-91b2d02e9f46">

**Comment by liu-si-han** [comment]
<img width="804" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/8ebf7e6c-ca72-4a91-9fbf-fa0772a02230">

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/f303b53f-2b77-47c0-ab7f-09e1f2018dd0)

**Comment by daowuwu** [comment]
![KJIGJU`U08F`WTHUY9~VSN3](https://github.com/umdreamer/leetcodeproblems/assets/132571490/7a3fae1c-fbf5-48f6-80ad-dfde56810658)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/28c593cf-3f9a-43ac-9bd0-610ab9d3862b)

**Comment by 12baoxingyu-6** [comment]
<img width="725" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/290e886a-51e4-4e60-afc5-fdf2e596de66">

**Comment by mafanjia** [comment]
![截屏4](https://github.com/umdreamer/leetcodeproblems/assets/132454776/fc1ff735-3c7b-4960-aa2f-c169d10cdf55)

**Comment by htywan** [comment]
![12](https://github.com/umdreamer/leetcodeproblems/assets/132428178/3aea16fb-51f6-479b-b785-cd865813fd3f)

**Comment by 123lrb** [comment]
![ID`7@L~31 Z`_M45 N8`Z3I](https://github.com/umdreamer/leetcodeproblems/assets/132526491/da91bb27-790e-4c27-9c06-0e7cc9a42b00)

**Comment by syr2212061031** [comment]
![LPF~5 CDZK{9JS$8YKAF7}A](https://github.com/umdreamer/leetcodeproblems/assets/132579828/379747af-53dd-4cd2-97cf-46cfe882459c)

**Comment by gusuning** [comment]
<img width="940" alt="屏幕截图 2023-05-15 211646" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/9c5736d4-3b2c-4a0c-8be2-eb4a70ab0b6a">

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/db1338bb-13d7-4fc7-bb25-96684e5edecb)

**Comment by 24zlx** [comment]
![联想截图_20230515213005](https://github.com/umdreamer/leetcodeproblems/assets/132560099/1420fdbd-5139-4c51-bf8c-55b9404090d5)

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/cdbde3b2-f91f-4576-aa8b-5c493082ea16)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-15 21 28 43" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/45ba0c28-283c-495d-b83d-f3eecf141f2b">

**Comment by naqianqpg** [comment]
![EA0XL(2~J328S_CY9HRN8KM](https://github.com/umdreamer/leetcodeproblems/assets/132567187/7456edd2-af09-406a-b5f5-2dc5fb69eaaa)

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/68db47e8-f557-4dee-956a-deca502472c3)

**Comment by bedauern** [comment]
<img width="813" alt="Snipaste_2023-05-15_21-48-23" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/ad5ca689-1e04-45d9-970c-3badf240a6e7">

**Comment by 686xiaozhang** [comment]
![QQ截图20230515215514](https://github.com/umdreamer/leetcodeproblems/assets/132082348/2165b68f-4e73-467f-97ca-991142bc112d)

**Comment by FXL1006** [comment]
<img width="483" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/0e9955de-c1a4-41c1-82df-7028dda4e95d">

**Comment by FXL1006** [comment]
<img width="483" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/a19a94a0-4cd5-4059-b987-6bae40629439">

**Comment by FXL1006** [comment]
<img width="800" alt="屏幕截图 2023-05-15 201441" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/865f004a-7ccf-4395-bb30-3222e29e1248">

**Comment by shylieisme** [comment]
![GTFPI`KBGYWGT926}}F6O}1](https://github.com/umdreamer/leetcodeproblems/assets/132582721/e01d224c-d7b0-4062-a9a6-cb538c2340ba)

**Comment by zyhzxy99** [comment]
![$6_6EL9LK )LJMTHXT18P(A](https://github.com/umdreamer/leetcodeproblems/assets/132050929/a7470146-ab82-4593-b492-8052c0c8a1f9)
