### ISSUE TITLE
2023.5.16 Problem: 66. Plus One

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#14]
66. Plus One
[Problem Link](https://leetcode.cn/problems/plus-one/)

You are given a large integer represented as an integer array digits, where each digits[i] is the ith digit of the integer. The digits are ordered from most significant to least significant in left-to-right order. The large integer does not contain any leading 0's.

Increment the large integer by one and return the resulting array of digits.

 

Example 1:
```
Input: digits = [1,2,3]
Output: [1,2,4]
Explanation: The array represents the integer 123.
Incrementing by one gives 123 + 1 = 124.
Thus, the result should be [1,2,4].
```
Example 2:
```
Input: digits = [4,3,2,1]
Output: [4,3,2,2]
Explanation: The array represents the integer 4321.
Incrementing by one gives 4321 + 1 = 4322.
Thus, the result should be [4,3,2,2].
```
Example 3:
```
Input: digits = [9]
Output: [1,0]
Explanation: The array represents the integer 9.
Incrementing by one gives 9 + 1 = 10.
Thus, the result should be [1,0].
``` 

Constraints:

* `1 <= digits.length <= 100`
* `0 <= digits[i] <= 9`
* `digits does not contain any leading 0's.`

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/17d7556e-7e72-43d2-b6da-342652bac8d2)

**Comment by mafanjia** [comment]
![截屏5](https://github.com/umdreamer/leetcodeproblems/assets/132454776/0e7d2919-5909-4b86-b7bb-6c36737c8c25)

**Comment by liu-si-han** [comment]
<img width="818" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/4352f051-2db9-4ee8-8529-ef9242d6ca95">

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/a98c1130-b03b-4f52-b0fc-00b711b66e78)

**Comment by bedauern** [comment]
<img width="834" alt="Snipaste_2023-05-16_18-29-32" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/cbb438a3-1b08-4648-bae3-a455a3695779">

**Comment by shylieisme** [comment]
![$5YO)WRYRSVC_78ZA{6TUU7](https://github.com/umdreamer/leetcodeproblems/assets/132582721/aada2ca5-7119-433c-8579-d67dbfe55f1e)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-16 18 26 23" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/9926971c-2524-4a68-b5b7-a0d6498badbd">

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/a7274514-5cd9-4e3a-a576-ff18e104bf60)

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/1fe50312-4fb7-45e6-8a94-4948dc8bd6a3)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-16 191812](https://github.com/umdreamer/leetcodeproblems/assets/117709686/33eaf2b0-d96c-4722-b30a-84afd91334c2)

**Comment by 123lrb** [comment]
![($C%MKC@OGW T9AFS9`G2`B](https://github.com/umdreamer/leetcodeproblems/assets/132526491/f5d9d4d6-e1e1-49eb-bae2-8a1370871e7d)

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/82ed14ef-c32e-4304-9442-24727f334d72)

**Comment by sjh397** [comment]
![屏幕截图 2023-05-16 175735](https://github.com/umdreamer/leetcodeproblems/assets/132568283/07f7c87c-b524-4e68-81aa-584deb141a5b)

**Comment by huangyumei1** [comment]
![QQ图片20230516202312](https://github.com/umdreamer/leetcodeproblems/assets/122475924/0c772682-79a4-4a81-a391-a92bc9f67db4)

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/065f4542-07f1-4091-bbf8-a1a4429d8d78)

**Comment by foxbou** [comment]
<img width="973" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/96d47854-76a8-4298-a56f-fa59f3f832b4">

**Comment by 12baoxingyu-6** [comment]
<img width="832" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/c6d43d3b-d364-4588-8dbc-891ef3a46c03">

**Comment by cuixiao02** [comment]
<img width="626" alt="截屏2023-05-16 21 07 14" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/115b0704-aae6-4db1-8975-46adf89ca69b">

**Comment by syr2212061031** [comment]
![6V7TTN}HRM{UF`9U(K%)FCC](https://github.com/umdreamer/leetcodeproblems/assets/132579828/739d5bb3-2047-4788-9cc8-d5a9cfcdbd64)

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/88044054-76f7-4770-b0ff-d0db19dba6da)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/d769bf21-d805-4193-b7bd-b81e133e213c)

**Comment by naqianqpg** [comment]
![Z~L3VM0E)EV$ZNP$~32`E3F](https://github.com/umdreamer/leetcodeproblems/assets/132567187/954328e8-4986-445a-a7a5-7c76734c2096)

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/0628bf98-d389-4709-9430-da6f1e3dc013)

**Comment by 686xiaozhang** [comment]
![QQ截图20230516211207](https://github.com/umdreamer/leetcodeproblems/assets/132082348/eacc40fd-dcf8-4109-b47c-13d6d01cac6f)

**Comment by tangyexi** [comment]
<img width="767" alt="屏幕截图 2023-05-16 214726" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/cd2d0948-cd99-4de9-8180-f341c57d003b">

**Comment by htywan** [comment]
![11](https://github.com/umdreamer/leetcodeproblems/assets/132428178/e352a16d-83ca-41a0-9042-19084695ac6e)

**Comment by 24zlx** [comment]
![联想截图_20230516215818](https://github.com/umdreamer/leetcodeproblems/assets/132560099/121cf963-a711-49b4-b04f-30d796ce5baf)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/1e951d41-d26f-4a4f-be55-969947bea11d)

**Comment by daowuwu** [comment]
![V2VV6M1XL)`CRDXY$V``J}5](https://github.com/umdreamer/leetcodeproblems/assets/132571490/c46a32cb-b64f-4ebc-93d3-4a549f0018a1)

**Comment by FXL1006** [comment]
<img width="880" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/c8f23720-ac49-4bb5-9c51-94e60d533fa7">

**Comment by zyhzxy99** [comment]
![S _2VPD{BTB%@ZJDB7~}@@A](https://github.com/umdreamer/leetcodeproblems/assets/132050929/36771451-717f-4147-85ba-8234a2cc9019)

**Comment by zangfushuo** [comment]
<img width="611" alt="截屏2023-05-16 22 51 06" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/5c0cb8bd-0366-4034-ad45-4d4bad96b554">

**Comment by gusuning** [comment]
<img width="1025" alt="屏幕截图 2023-05-17 124419" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/624c615b-77c5-4273-9200-d4fb9b9da32c">
