### ISSUE TITLE
2023.5.17 Problem: 67. Add Binary

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#15]
67. Add Binary
[Problem Link](https://leetcode.cn/problems/add-binary/)

Given two binary strings a and b, return their sum as a binary string.

Example 1:
```
Input: a = "11", b = "1"
Output: "100"
```
Example 2:
```
Input: a = "1010", b = "1011"
Output: "10101"
``` 

Constraints:

* 1 <= a.length, b.length <= 104
* a and b consist only of '0' or '1' characters.
* Each string does not contain leading zeros except for the zero itself.

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/81998ea9-2033-4302-9002-bac91dd98293)

**Comment by gusuning** [comment]
<img width="838" alt="屏幕截图 2023-05-17 130405" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/7958efeb-1ed4-4243-9fde-4c4f603a6d5c">

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/425578b2-b071-471c-b993-120b4fd4f0c8)

**Comment by zyhzxy99** [comment]
![7 YZSQ5M`OM~5F29K2U0I01](https://github.com/umdreamer/leetcodeproblems/assets/132050929/9dbf4bda-6d89-4687-bd23-4186ce6d8ff6)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/01e0a03c-7cff-4624-8810-2eea505c295f)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/cd7049dc-179c-4e6c-ad7e-1b9276445315)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/c84588fc-47dd-493a-a558-e8fbb484cb9f)

**Comment by 686xiaozhang** [comment]
![QQ截图20230517170027](https://github.com/umdreamer/leetcodeproblems/assets/132082348/5b39697e-48af-4a78-b821-09c056b05254)

**Comment by liu-si-han** [comment]
<img width="800" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/abfea82b-44a1-45ce-9e71-ced1f1548a5f">

**Comment by mafanjia** [comment]
![截屏6](https://github.com/umdreamer/leetcodeproblems/assets/132454776/272f2a2a-038d-49ac-8080-daf329b96e10)

**Comment by syr2212061031** [comment]
![K 9JZEU5T` J%RK@406` 84](https://github.com/umdreamer/leetcodeproblems/assets/132579828/3df29279-64de-4dc0-9a7f-1a6822099436)

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/ebecb149-c637-4af1-8738-3046a85b87ed)

**Comment by tangyexi** [comment]
<img width="829" alt="屏幕截图 2023-05-17 174004" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/4d52c1a1-8b0c-4fb7-a51d-f4cc75a4f256">

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/81643a1d-2cd5-4e97-9cb8-17e419898d21)

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/6a0ee620-61c3-47ae-818d-6f0528f51c5a)

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/4b1cc962-290c-4a8e-9ee5-a5bc09ab6257)

**Comment by 12baoxingyu-6** [comment]
<img width="813" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/d68e544c-8cac-42f3-8749-165888902b36">

**Comment by zangfushuo** [comment]
<img width="632" alt="截屏2023-05-17 18 55 43" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/b5613ca6-6287-44b4-8a7a-7f8bb9a257fe">

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-17 173715](https://github.com/umdreamer/leetcodeproblems/assets/117709686/486fd55c-1997-4a4b-8123-4606d798cc6f)

**Comment by cuixiao02** [comment]
![Uploading A08E7191-787E-420B-AD09-CCBA13B7A6ED.jpeg…]()

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/a40ac994-5ecd-4eaa-acc8-80710054f1a0)

**Comment by bedauern** [comment]
<img width="766" alt="Snipaste_2023-05-17_20-48-21" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/ae56b775-cc17-4eca-a920-c51ef9b72e17">

**Comment by htywan** [comment]
![121](https://github.com/umdreamer/leetcodeproblems/assets/132428178/8ebfe3fd-c372-4593-b602-9858dee831a5)

**Comment by 24zlx** [comment]
![联想截图_20230517205213](https://github.com/umdreamer/leetcodeproblems/assets/132560099/826a0942-9219-4a1f-8409-218198cb1a50)

**Comment by 123lrb** [comment]
![@D@{F 041}A} BH2_T3J}A](https://github.com/umdreamer/leetcodeproblems/assets/132526491/464b0520-f8d7-4c38-b4b3-44f13abd4e7a)

**Comment by daowuwu** [comment]
![{JHOV6(G`K6NE ~TNI84SKE](https://github.com/umdreamer/leetcodeproblems/assets/132571490/8061bbbe-91b6-43e1-81d4-9109ed8e99fe)

**Comment by huangyumei1** [comment]
![QQ图片20230517211816](https://github.com/umdreamer/leetcodeproblems/assets/122475924/5090f28a-059e-4d36-b91d-600c6beb804c)

**Comment by naqianqpg** [comment]
![`C_TL5SL~`2C68@{S~SRC7O](https://github.com/umdreamer/leetcodeproblems/assets/132567187/f6b82f22-cb90-4574-8c0a-c0bc7d6cab29)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-17 21 24 11" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/7b65a0a3-7b6b-4b21-9bc3-d20dad47ab61">

**Comment by shylieisme** [comment]
![F_J5%M2LAT}36HKONBAKBUY](https://github.com/umdreamer/leetcodeproblems/assets/132582721/5da31415-0dff-4989-9e73-1634d40e98f4)

**Comment by foxbou** [comment]
<img width="952" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/7abe851c-ddad-4493-bfc0-b1bc1e057d00">

**Comment by FXL1006** [comment]
<img width="790" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/b99ff109-c6c3-4e68-9e0c-61073d05eaa9">

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/8707f659-898c-44ce-81a7-65227130e729)

**Comment by bedauern** [comment]
<img width="843" alt="Snipaste_2023-05-18_21-01-38" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/6bcb2526-f784-4c47-aea5-b5fd607eaa1b">
