### ISSUE TITLE
2023.5.18 Problem: 69. Sqrt(x)

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#16]
69. Sqrt(x)
[Problem Link](https://leetcode.cn/problems/sqrtx/)

Given a non-negative integer x, return the square root of x rounded down to the nearest integer. The returned integer should be non-negative as well.

You must not use any built-in exponent function or operator.

For example, do not use pow(x, 0.5) in c++ or x ** 0.5 in python.
 

Example 1:
```
Input: x = 4
Output: 2
Explanation: The square root of 4 is 2, so we return 2.
```
Example 2:
```
Input: x = 8
Output: 2
Explanation: The square root of 8 is 2.82842..., and since we round it down to the nearest integer, 2 is returned.
``` 

Constraints:
* `0 <= x <= 231 - 1`

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/b22eceee-d3fa-433f-aa5f-eed58a4c211a)

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/3d85b74a-1c29-4a20-b898-24388c1c882f)

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/909843d8-76dc-4eb0-99e9-1a10c692a7ed)

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/9cc485f2-1d28-406d-a3cb-39254af2737c)

**Comment by cuixiao02** [comment]
<img width="656" alt="截屏2023-05-18 14 30 54" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/c36f958a-2b51-44be-b608-b2e82af02571">

**Comment by liu-si-han** [comment]
<img width="796" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/e77bcaf3-e218-40c0-813e-3ccc6ab578a7">

**Comment by daowuwu** [comment]
![)8J7 @QG@T@0IQ572MSTSSG](https://github.com/umdreamer/leetcodeproblems/assets/132571490/ec5a8cf7-edfd-4d08-8eb2-49b4dbf7f28a)

**Comment by 686xiaozhang** [comment]
![QQ截图20230518152109](https://github.com/umdreamer/leetcodeproblems/assets/132082348/44ecda03-aa55-4eb3-be4e-6e0dd2adc28b)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/484dd8ce-c656-4797-8db6-4e1b0e6ddd86)

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/1ac680e6-3b1c-4066-925e-3e82606ba61d)

**Comment by huangyumei1** [comment]
![QQ图片20230518172149](https://github.com/umdreamer/leetcodeproblems/assets/122475924/ae5d7829-fb45-4bd7-bc5b-1c9e098140eb)

**Comment by mafanjia** [comment]
![截屏7](https://github.com/umdreamer/leetcodeproblems/assets/132454776/8395e8f3-f495-499b-90be-4aa4ee051fb5)

**Comment by gusuning** [comment]
<img width="933" alt="屏幕截图 2023-05-18 174442" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/1ef08517-b370-4ce7-8953-819852916b56">

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-18 150605](https://github.com/umdreamer/leetcodeproblems/assets/117709686/7cb88364-5906-4969-8082-72ec9dbebdb4)

**Comment by foxbou** [comment]
<img width="1076" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/3a567427-b398-4374-bd3a-c2081e00492f">

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/fa5bce4c-a887-4910-9acf-0019ab3c5b88)

**Comment by tangyexi** [comment]
<img width="907" alt="屏幕截图 2023-05-18 184237" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/c098ecee-1e4c-4f9c-9674-787165db4338">

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/ecfc2751-c1cf-46d5-8381-96aeca5320d9)

**Comment by xkqwww** [comment]
![5 18晚](https://github.com/umdreamer/leetcodeproblems/assets/132559761/6d7c5f1e-d4b1-46a0-a425-4135ea0af3dc)

**Comment by 12baoxingyu-6** [comment]
<img width="848" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/26d4cb4d-f917-4e4c-b642-5b3baec90acc">

**Comment by naqianqpg** [comment]
![1X5HO$T7@4Q$Z3@2JW1` XK](https://github.com/umdreamer/leetcodeproblems/assets/132567187/ef6ff3c8-9e8d-46fe-9188-30d0c5c5471b)

**Comment by 24zlx** [comment]
![联想截图_20230518204923](https://github.com/umdreamer/leetcodeproblems/assets/132560099/1eb50f27-b7ea-470d-bc12-d7adc329e0df)

**Comment by FXL1006** [comment]
<img width="759" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/695ba4f9-e7ac-4bea-b015-8b43be64fb66">

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/42bd9388-a3bd-4a28-ba86-cb030bdf181b)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-18 21 33 01" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/bea2c3a5-6c05-4708-ae59-df0f4e89bab4">

**Comment by htywan** [comment]
![1](https://github.com/umdreamer/leetcodeproblems/assets/132428178/a244d027-8d85-4942-8aa1-194ed03fb9ad)

**Comment by 123lrb** [comment]
![F({2RU~GU`F0@BSH3R 8I3U](https://github.com/umdreamer/leetcodeproblems/assets/132526491/4259fdac-cb8d-4512-b767-2e20874ff346)

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/407b6892-ca89-4015-829e-7b66d71a7bbe)

**Comment by syr2212061031** [comment]
![TY0W}){`P%TCMNYJ@NSI8{X](https://github.com/umdreamer/leetcodeproblems/assets/132579828/33014814-aa2d-44f4-8ecf-34b3b364a23a)

**Comment by zyhzxy99** [comment]
![`K91 6FL%%M(P_V0PC1 H~2](https://github.com/umdreamer/leetcodeproblems/assets/132050929/816e2759-5829-4dba-8827-f494f7df2a5e)

**Comment by shylieisme** [comment]
![Y_SOAYMU~IHZANQG}C_T2YT](https://github.com/umdreamer/leetcodeproblems/assets/132582721/78701694-cefb-41b2-a936-b09b8da39182)

**Comment by zangfushuo** [comment]
<img width="635" alt="截屏2023-05-18 22 58 42" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/c2578d23-fdbc-40ee-8ab4-13036f6b041f">

**Comment by bedauern** [comment]
<img width="843" alt="Snipaste_2023-05-18_21-01-38" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/bd39eafa-77a8-4a01-900e-299767660782">
