### ISSUE TITLE
2023.5.19 Problem: 70. Climbing Stairs

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#17]
70. Climbing Stairs

You are climbing a staircase. It takes n steps to reach the top.

Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?

 

Example 1:
```
Input: n = 2
Output: 2
Explanation: There are two ways to climb to the top.
1. 1 step + 1 step
2. 2 steps
```
Example 2:
```
Input: n = 3
Output: 3
Explanation: There are three ways to climb to the top.
1. 1 step + 1 step + 1 step
2. 1 step + 2 steps
3. 2 steps + 1 step
``` 

Constraints:
* `1 <= n <= 45`

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/9146c4a6-0f5b-472f-be4a-4b02bf011fc7)

**Comment by liu-si-han** [comment]
<img width="803" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/36533e5d-bfaf-4074-8783-91fab127d2fa">

**Comment by tangyexi** [comment]
<img width="826" alt="屏幕截图 2023-05-19 200402" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/ca529dc6-c437-4606-a679-422f9e14b6b9">

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/271bf9e9-fbcd-409e-a21f-cfc64797bbaa)

**Comment by 686xiaozhang** [comment]
![QQ截图20230519201921](https://github.com/umdreamer/leetcodeproblems/assets/132082348/fefdef5b-8e4d-40af-811b-f1b333b2d974)

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/3c35a795-c987-4809-b291-2208e9cbd828)

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/bfb580e9-82f7-4faf-b045-4f5ae1c202cd)

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/32c888a1-a708-4eb9-8a83-331bec143384)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-19 20 53 10" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/9e123564-3ecf-4d14-a2bf-e714872f466b">

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/4ab1cb38-8cad-48db-9250-d4be12d6d26f)

**Comment by huangyumei1** [comment]
![QQ图片20230519210104](https://github.com/umdreamer/leetcodeproblems/assets/122475924/0f1b04be-8719-4202-aa7e-1c2d63ba2b1a)

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/23be5a06-cc56-469f-92fd-3d98ed34327f)

**Comment by 123lrb** [comment]
![`OWFMWF{E0 FG7FBTL)7D%5](https://github.com/umdreamer/leetcodeproblems/assets/132526491/cb29aa6e-daf8-4512-9879-2cc9b4aee714)

**Comment by zyhzxy99** [comment]
![$V66)`7IP6SP9BS)%`RCUUJ](https://github.com/umdreamer/leetcodeproblems/assets/132050929/9c313c28-c483-432b-9a66-2ccf175959f0)

**Comment by bedauern** [comment]
<img width="812" alt="Snipaste_2023-05-19_21-14-16" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/ffe539a8-b946-428c-b84c-bce23af8a6ac">

**Comment by daowuwu** [comment]
![JK_O}SSF8D {GJHWZ6IW0](https://github.com/umdreamer/leetcodeproblems/assets/132571490/03755ae9-f58b-47e6-a07b-7385c6883251)

**Comment by shylieisme** [comment]
![$QT6S~JLFR XGWYX K(6TX0](https://github.com/umdreamer/leetcodeproblems/assets/132582721/580bf8dd-db26-4495-af58-30bce000a993)

**Comment by foxbou** [comment]
<img width="1025" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/6ec70d70-c03e-44a5-a6db-45f8a9c606d2">

**Comment by FXL1006** [comment]
<img width="595" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/7d6f196d-cb57-4e07-9c32-6d63376329a4">

**Comment by cuixiao02** [comment]
![Uploading 截屏2023-05-19 21.31.12.png…]()

**Comment by cuixiao02** [comment]
![Uploading 截屏2023-05-19 21.31.12.png…]()

**Comment by cuixiao02** [comment]
<img width="649" alt="截屏2023-05-19 21 31 12" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/eced1914-baf0-4e17-b8fa-45db74348e06">

**Comment by 12baoxingyu-6** [comment]
<img width="724" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/95c61b26-581c-4368-878f-02235b60edf5">

**Comment by cuixiao02** [comment]
<img width="649" alt="截屏2023-05-19 21 31 12" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/53263282-89ff-4f44-9807-914b42b4199b">

**Comment by FXL1006** [comment]
<img width="210" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/2a90e91f-aad3-4ea2-9e28-379180aa33ed">

**Comment by syr2212061031** [comment]
![DSI9%6@U5LMG23UDYCF ON](https://github.com/umdreamer/leetcodeproblems/assets/132579828/25a2d4b2-56be-4687-af19-19f6339e342f)

**Comment by mafanjia** [comment]
![截屏8](https://github.com/umdreamer/leetcodeproblems/assets/132454776/d3007777-d18d-4afc-a741-46673afcecd1)

**Comment by htywan** [comment]
![11](https://github.com/umdreamer/leetcodeproblems/assets/132428178/77105e3b-4e49-4d95-b478-602fe4608614)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-19 214650](https://github.com/umdreamer/leetcodeproblems/assets/117709686/a8f2c78e-500e-4737-8021-d3da2a9856b8)

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/e0a9b9d7-3e33-4994-9a12-505bf778845f)

**Comment by gusuning** [comment]
<img width="1082" alt="屏幕截图 2023-05-19 220547" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/1d985ed2-0473-4228-add0-56519c28609b">

**Comment by 24zlx** [comment]
![联想截图_20230519222409](https://github.com/umdreamer/leetcodeproblems/assets/132560099/bae81711-10b7-4869-a4b5-c825efe9adce)

**Comment by naqianqpg** [comment]
![@8K8AV$%ZM(35(PFA0$Q ZJ](https://github.com/umdreamer/leetcodeproblems/assets/132567187/b44e46c0-6c2a-4401-a167-ef2383631fc3)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/4cdb7509-8774-4dbc-8d2d-e417ceb6bbe4)

**Comment by yeyuxq** [comment]
<img width="580" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/128273789/48677a27-61ce-42c2-b119-983bdd7bed40">

**Comment by zangfushuo** [comment]
<img width="617" alt="截屏2023-05-19 23 20 22" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/b9aa8383-da7d-4b1d-a5d4-a403935360c5">
