### ISSUE TITLE
2023.5.20 Problem: 83. Remove Duplicates from Sorted List 

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#18]
83. Remove Duplicates from Sorted List
[Problem Link](https://leetcode.cn/problems/remove-duplicates-from-sorted-list/)

Given the head of a sorted linked list, delete all duplicates such that each element appears only once. Return the linked list sorted as well.

Example 1:
![image](https://github.com/umdreamer/leetcodeproblems/assets/15782682/7b8242f3-c8a1-4888-9e0d-131d15c0e7eb)

```
Input: head = [1,1,2]
Output: [1,2]
```
Example 2:
![image](https://github.com/umdreamer/leetcodeproblems/assets/15782682/f0d641f5-d338-42c1-88f2-17ea9922515c)

```
Input: head = [1,1,2,3,3]
Output: [1,2,3]
``` 

Constraints:

* The number of nodes in the list is in the range `[0, 300]`.
* `-100 <= Node.val <= 100`
* The list is guaranteed to be sorted in ascending order.

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/8aeb15a8-50f7-4015-addf-e49af0834661)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/5e7062ea-cc09-4032-9518-63ff80168094)

**Comment by liu-si-han** [comment]
<img width="809" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/69e1b978-7353-45a2-9160-18c5183c1ee2">

**Comment by shylieisme** [comment]
![RRE4)%MFG15RK3QIYM22P77](https://github.com/umdreamer/leetcodeproblems/assets/132582721/1e0b3414-9002-47f3-aba0-6c9becfe3b4e)

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/4a95ec9e-1d80-4b2c-95d3-de15029de518)

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/e69bdcca-b117-4932-8769-8bb66cdbb01b)

**Comment by bedauern** [comment]
<img width="816" alt="Snipaste_2023-05-20_17-41-00" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/b3a71a03-0511-4df6-a154-0e756f3c6ecf">

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/2e31ccb2-a966-442f-85dd-6b3f97e8f79d)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-20 17 49 34" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/4d523f67-174f-4174-a3ad-122cacfc15ae">

**Comment by tangyexi** [comment]
<img width="934" alt="屏幕截图 2023-05-20 175309" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/7060e3ce-89c1-413d-9fbe-9894d18c630f">

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/5cfc4458-b4c5-4b4e-a312-96ed9a320867)

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/c8bd8f9f-6132-4936-9bf4-486bac781d1f)

**Comment by huangyumei1** [comment]
![QQ图片20230520195116](https://github.com/umdreamer/leetcodeproblems/assets/122475924/3038141f-51d5-4c82-bedf-f138e78c60a8)

**Comment by mafanjia** [comment]
![截屏9](https://github.com/umdreamer/leetcodeproblems/assets/132454776/3f583d5b-7e24-4483-ac30-7a518a229ddd)

**Comment by gusuning** [comment]
<img width="1009" alt="屏幕截图 2023-05-20 203452" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/25a86187-dc02-4cb5-8162-c9fbd51c7774">

**Comment by 12baoxingyu-6** [comment]
<img width="794" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/6707b203-132b-41be-a2ac-b578648f3a00">

**Comment by htywan** [comment]
![1](https://github.com/umdreamer/leetcodeproblems/assets/132428178/cc0958d7-1f25-4e15-ba65-92206d01788b)

**Comment by 123lrb** [comment]
![K1ALKRU%~WYHEF67~K{BWIJ](https://github.com/umdreamer/leetcodeproblems/assets/132526491/746511a2-55fe-45cc-8c4b-be4897982b6f)

**Comment by 24zlx** [comment]
![联想截图_20230520212831](https://github.com/umdreamer/leetcodeproblems/assets/132560099/2426d1e7-6735-43a2-b1b4-9263f7a7c36c)

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/8bca5b25-817e-4e2b-87e6-c00cfda95225)

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/0568284a-1b64-4638-8bf4-82eecc35ebad)

**Comment by cuixiao02** [comment]
<img width="661" alt="截屏2023-05-20 21 41 20" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/0ccf6471-5514-4e82-8a9f-bf2d5e74aa3b">

**Comment by daowuwu** [comment]
![0M5RYK08OIH)7XNB)8QJX(Q](https://github.com/umdreamer/leetcodeproblems/assets/132571490/a90e9cb4-2c94-4a6b-9ef5-650cb076245e)

**Comment by syr2212061031** [comment]
![A 7@58_43ASRWEA4`KH1%Y](https://github.com/umdreamer/leetcodeproblems/assets/132579828/fa150aee-4284-4379-9ea0-ca9f5e1abd81)

**Comment by FXL1006** [comment]
<img width="783" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/2ddf6c56-c21b-4d16-ac75-386e445d003c">

**Comment by 686xiaozhang** [comment]
![QQ截图20230520220900](https://github.com/umdreamer/leetcodeproblems/assets/132082348/656888d3-f0e0-43bd-a2ea-19ff735b2be3)

**Comment by naqianqpg** [comment]
![5YVN__8Z`Q%I H9FRQBQS`E](https://github.com/umdreamer/leetcodeproblems/assets/132567187/c1f74b97-4925-45fe-a92e-2867f7222f64)

**Comment by zangfushuo** [comment]
<img width="622" alt="截屏2023-05-20 22 22 41" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/9c122d04-5a88-46be-89ac-49cd42cfd2e1">

**Comment by zyhzxy99** [comment]
![W4816E2MB`6GYGLOCZBM NM](https://github.com/umdreamer/leetcodeproblems/assets/132050929/66dabc8b-300f-4be4-8d10-e5973403d468)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-20 231817](https://github.com/umdreamer/leetcodeproblems/assets/117709686/a7a4509d-e51f-4e00-af69-e3dbe9adfef1)
