### ISSUE TITLE
2023.5.22 Problem: 118. Pascal's Triangle

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#19]
118. Pascal's Triangle
[Problem Link](https://leetcode.cn/problems/pascals-triangle/)

Given an integer numRows, return the first numRows of Pascal's triangle.

In Pascal's triangle, each number is the sum of the two numbers directly above it as shown:

![image](https://github.com/umdreamer/leetcodeproblems/assets/15782682/4c31124d-75fa-4610-a7cc-2be5b0bc70cc)

 

Example 1:
```
Input: numRows = 5
Output: [[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]
```
Example 2:
```
Input: numRows = 1
Output: [[1]]
``` 

Constraints:

* `1 <= numRows <= 30`

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/8d7eeec0-2f81-42a9-9c2c-1ae84380ce05)

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/b0d839d6-d391-4fc5-ab28-49e033f554a3)

**Comment by huangyumei1** [comment]
![QQ图片20230522162450](https://github.com/umdreamer/leetcodeproblems/assets/122475924/79af336e-3daa-474d-a8ba-d0c8719ba521)

**Comment by tangyexi** [comment]
<img width="851" alt="屏幕截图 2023-05-22 164251" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/4c5ade55-be90-4ca1-ac7f-28e9b970c13e">

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/96855c94-6826-4b88-9507-4f2987f9c877)

**Comment by cuixiao02** [comment]
<img width="603" alt="截屏2023-05-22 18 38 49" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/018071fd-c6d5-4a41-bd00-bf140433f6ae">

**Comment by zangfushuo** [comment]
<img width="618" alt="截屏2023-05-22 18 41 57" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/6a193deb-6b61-45dd-a10c-cad3ae5684c3">

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-22 18 35 51" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/ae17f10c-0724-4828-8657-de78594e4ce3">

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/8f784b29-ba50-4288-b75a-05cfd2213b72)

**Comment by daowuwu** [comment]
![G3UV 8V`} A{)AT)PLSSDS](https://github.com/umdreamer/leetcodeproblems/assets/132571490/2b43f8a7-5865-4097-92d9-7e1004e6954c)

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/e20e342a-6efb-457e-bc2d-61b25f34e8fd)

**Comment by 686xiaozhang** [comment]
![QQ截图20230522190338](https://github.com/umdreamer/leetcodeproblems/assets/132082348/e9712ea1-ff0b-4d26-9e27-93e327fcbb89)

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/adcc8151-c8cd-44f7-aa9f-6c8fd4bea396)

**Comment by 123lrb** [comment]
![DJ2T $ZW0GBXZ2TF7ZWDZ 8](https://github.com/umdreamer/leetcodeproblems/assets/132526491/5729a48f-661d-4256-88b8-185b15256650)

**Comment by mafanjia** [comment]
![截屏10](https://github.com/umdreamer/leetcodeproblems/assets/132454776/338d988d-288e-4bc6-bab4-75ee90eb45ac)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-22 202620](https://github.com/umdreamer/leetcodeproblems/assets/117709686/290354de-793d-47cd-b2f3-5bf506c74284)

**Comment by liu-si-han** [comment]
<img width="770" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/759c29bf-9890-4135-90bc-f6d7fcec2f1b">

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/df42db00-c9a2-4044-a844-e1f18e9ea0ff)

**Comment by syr2212061031** [comment]
![U8Z9HB{_6NMJ)77U30}HBP6](https://github.com/umdreamer/leetcodeproblems/assets/132579828/a6583a74-64d8-4ed4-8f40-7a47f62ae59f)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/e5b72d06-3375-4123-8dcb-9cd903441055)

**Comment by shylieisme** [comment]
![8{B8MNPM_7~WJ$8J6GK~J62](https://github.com/umdreamer/leetcodeproblems/assets/132582721/bed6a508-ecc4-45eb-ac82-0bc246105086)

**Comment by FXL1006** [comment]
<img width="92" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/47814afb-ec8e-435a-a810-c5508e4d1ec7">

**Comment by FXL1006** [comment]
<img width="540" alt="屏幕截图 2023-05-22 192456" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/b6761c37-b8b9-4d5f-ae69-abf3ee463d1c">

**Comment by bedauern** [comment]
<img width="802" alt="Snipaste_2023-05-22_21-14-13" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/4338c696-a1bc-419a-8acb-fe2900faa4fd">

**Comment by foxbou** [comment]
<img width="886" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/eb22c2b5-be70-4b3d-8229-5410b0129438">

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/e1b2b5b4-4bd6-4440-ab78-22f1d43d6433)

**Comment by 24zlx** [comment]
![联想截图_20230522212752](https://github.com/umdreamer/leetcodeproblems/assets/132560099/561ea11a-6350-4121-8e7c-c0ac871a8a9a)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/1c9bd04a-6536-4586-8c4a-9b34cc275970)

**Comment by htywan** [comment]
![1](https://github.com/umdreamer/leetcodeproblems/assets/132428178/a203ff44-e839-4bb9-865b-300fa76e23b1)

**Comment by naqianqpg** [comment]
![NXGU%36OMTO0XM1%`3K% V7](https://github.com/umdreamer/leetcodeproblems/assets/132567187/3ee7a5e8-c69a-4301-b409-d4bb7e4328a8)

**Comment by gusuning** [comment]
<img width="896" alt="屏幕截图 2023-05-22 214123" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/4fef5484-99b8-4e32-96d0-047f7ecfafab">

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/4af6f2fb-c177-4fb0-9c4f-6f92a871134b)

**Comment by 12baoxingyu-6** [comment]
<img width="798" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/7b9af4ba-50a8-4298-87c7-327aec2f9ac6">
