### ISSUE TITLE
2023.05.23 Problem: 119. Pascal's Triangle II

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#20]
119. Pascal's Triangle II
[Problem Link](https://leetcode.cn/problems/pascals-triangle-ii/)

Given an integer rowIndex, return the rowIndexth (0-indexed) row of the Pascal's triangle.

In Pascal's triangle, each number is the sum of the two numbers directly above it as shown:
![image](https://github.com/umdreamer/leetcodeproblems/assets/15782682/b80cf36b-93c7-4cb5-ba3c-c2b7fa240e99)

 

Example 1:
```
Input: rowIndex = 3
Output: [1,3,3,1]
```
Example 2:
```
Input: rowIndex = 0
Output: [1]
```
Example 3:
```
Input: rowIndex = 1
Output: [1,1]
``` 

Constraints:

* `0 <= rowIndex <= 33`

Follow up: Could you optimize your algorithm to use only `O(rowIndex)` extra space?

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/023e7047-3b55-4aae-84ea-be8b53d23509)

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/619a1830-aa61-4fd3-904c-8feb7a7b65f6)

**Comment by tangyexi** [comment]
<img width="883" alt="屏幕截图 2023-05-23 161055" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/cc1b8f78-82d5-4fae-80f6-cb6a97196c4b">

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/afdb3bf0-50e2-4927-bccc-d590d95a1003)

**Comment by liu-si-han** [comment]
<img width="794" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/e9218db0-f113-46a3-8ccf-53e84ff7e64b">

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/ca03f299-b26e-466b-a71f-442a9fc64368)

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/4b8afafe-2ce0-4688-9ea6-4be11e09dedc)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-23 124620](https://github.com/umdreamer/leetcodeproblems/assets/117709686/bfb902c1-3f69-46a1-a150-abb6c94b8636)

**Comment by daowuwu** [comment]
![8C P4U4N9T75NPJ(%JF@TU7](https://github.com/umdreamer/leetcodeproblems/assets/132571490/caed235c-744a-462c-88f6-63564f153609)

**Comment by cuixiao02** [comment]
<img width="632" alt="截屏2023-05-23 19 13 34" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/909c8ffb-7b62-41dc-9ab5-835da2d2d5a3">

**Comment by huangyumei1** [comment]
![QQ图片20230523200215](https://github.com/umdreamer/leetcodeproblems/assets/122475924/016f69ac-2ed7-4d18-86bc-af6d92e18b7f)

**Comment by FXL1006** [comment]
<img width="811" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/67081c73-a6b8-4a61-97fe-df145c8e68db">

**Comment by mafanjia** [comment]
![截屏11](https://github.com/umdreamer/leetcodeproblems/assets/132454776/306f9f2e-7cf8-4f32-818e-83cb468e45b0)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/627ef7a6-14d3-4b8c-abbf-5d52a934c180)

**Comment by naqianqpg** [comment]
![B)LY7Y~%$E@TB2A@%6ID6LK](https://github.com/umdreamer/leetcodeproblems/assets/132567187/2ace7740-36b1-4dfe-8f52-eddffa87e954)

**Comment by foxbou** [comment]
<img width="865" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/c7d65c29-796e-41b3-87db-e8135d1455d4">

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/3c2958b8-5a67-4f26-8d8b-3cbdb2a9f889)

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/4f75a9b6-afdf-4c3f-9a26-ec7d57d0b005)

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/585ba406-5f65-4446-b42c-b556af0f5c6e)

**Comment by htywan** [comment]
![2](https://github.com/umdreamer/leetcodeproblems/assets/132428178/6327d79d-0b7d-415f-85fb-e378f6cdd418)

**Comment by bedauern** [comment]
<img width="788" alt="Snipaste_2023-05-23_21-13-13" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/2cc99e7a-c282-48fc-a8a1-069a49a7fa11">

**Comment by 686xiaozhang** [comment]
![QQ截图20230523212453](https://github.com/umdreamer/leetcodeproblems/assets/132082348/1678fa15-1af3-4ccd-9364-83189fe11abd)

**Comment by 123lrb** [comment]
![T{YFOQE2MEJB 4S_}BVSK6](https://github.com/umdreamer/leetcodeproblems/assets/132526491/3426abe2-d5d5-442b-96b8-2229e55b959a)

**Comment by 12baoxingyu-6** [comment]
<img width="810" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/a6bd6f66-76c0-40b6-97cc-729eb50060d3">

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-22 18 35 51" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/8d23d01b-1b74-492f-998d-ba3f732c193b">

**Comment by shylieisme** [comment]
![EEM$ $ R0N64H`}Y8$Q$H9R](https://github.com/umdreamer/leetcodeproblems/assets/132582721/b3ebecec-6059-47bf-a8c7-3603f216dc69)

**Comment by shylieisme** [comment]
![A 0QY_{UN72HJR4LJLH(~YJ](https://github.com/umdreamer/leetcodeproblems/assets/132582721/719cb2f1-1d11-4a9f-b8f3-d42a69d5588f)

**Comment by 24zlx** [comment]
![联想截图_20230523220002](https://github.com/umdreamer/leetcodeproblems/assets/132560099/cbda8472-a0f8-4d86-b8af-4e1892879ddb)

**Comment by syr2212061031** [comment]
![1_HLR86DL(LCY3FHM_O5_ L](https://github.com/umdreamer/leetcodeproblems/assets/132579828/f9d74da8-659f-42e7-8009-6ba6210cd3e9)

**Comment by zangfushuo** [comment]
<img width="369" alt="截屏2023-05-23 21 59 57" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/b8fc2ee6-8bb1-49c2-90e6-9d620b5f3371">

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/e0de59b6-1f1d-41c0-b669-6a057f013506)

**Comment by gusuning** [comment]
<img width="979" alt="屏幕截图 2023-05-23 221822" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/aab9a4c6-652c-4a7e-9c0f-316a3d5156bd">

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/ad848b86-0475-4edc-886a-3f2db8b9169b)
