### ISSUE TITLE
2023.05.24 Problem: 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#21]
121. Best Time to Buy and Sell Stock
[Problem Link](https://leetcode.cn/problems/best-time-to-buy-and-sell-stock/)

You are given an array prices where prices[i] is the price of a given stock on the ith day.

You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.

Return the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.

 

Example 1:
```
Input: prices = [7,1,5,3,6,4]
Output: 5
Explanation: Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5.
Note that buying on day 2 and selling on day 1 is not allowed because you must buy before you sell.
```
Example 2:
```
Input: prices = [7,6,4,3,1]
Output: 0
Explanation: In this case, no transactions are done and the max profit = 0.
``` 

Constraints:

* `1 <= prices.length <= 105`
* `0 <= prices[i] <= 104`

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/57b3c90c-0a58-40d4-94fa-c790b95905e2)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/5d711867-1c5e-4413-88f9-6e37a69f9b76)

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/f8799b66-8839-49d2-8478-c727f99a0226)

**Comment by 123lrb** [comment]
![2X$Y XDO~FU`QN33S}JJ4(S](https://github.com/umdreamer/leetcodeproblems/assets/132526491/b7796a2e-2579-4c7d-bfc0-accc9cedaee6)

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/9c7d41d8-3acd-4b34-a450-f626b35cd109)

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/feef6bb4-a04c-4a17-aebf-bae4dc677152)

**Comment by cuixiao02** [comment]
<img width="631" alt="截屏2023-05-24 16 56 08" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/d163556b-f4d9-43d6-8d6b-721dad7a5262">

**Comment by liu-si-han** [comment]
<img width="802" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/25cee71c-33d8-4c9f-8c78-2f9509f6dec1">

**Comment by huangyumei1** [comment]
![QQ图片20230524171101](https://github.com/umdreamer/leetcodeproblems/assets/122475924/e751fca3-6079-4ebd-80ee-f4716913d81a)

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/70b557e3-cb4d-4398-84a1-29e20ad69cb6)

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/c5d8c238-f913-4d5a-9bca-b60dd320fcee)

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/bdaa2844-ae6a-4f03-8bc2-f59b1d52e038)

**Comment by naqianqpg** [comment]
![1CYM@PRUND($}WWCGCXTRDO](https://github.com/umdreamer/leetcodeproblems/assets/132567187/d98f96e1-f41e-47a9-94b7-996ef5d7a43c)

**Comment by daowuwu** [comment]
![PWF$YQTYGOUY6%Z OH{ 1 X](https://github.com/umdreamer/leetcodeproblems/assets/132571490/3149284c-8bd7-4004-a15c-78da1836438d)

**Comment by tangyexi** [comment]
<img width="873" alt="屏幕截图 2023-05-24 183155" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/ee6c4588-d8f3-4910-ad93-ba18e7d74924">

**Comment by 686xiaozhang** [comment]
![QQ截图20230524191623](https://github.com/umdreamer/leetcodeproblems/assets/132082348/91ed4425-9ca8-4b38-a1b7-c37a542d70cf)

**Comment by mafanjia** [comment]
![截屏12](https://github.com/umdreamer/leetcodeproblems/assets/132454776/2572f0e4-13bf-41f8-b27a-bbf8fe5f8903)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-24 110729](https://github.com/umdreamer/leetcodeproblems/assets/117709686/b2634ad0-bbca-4a6f-88a2-fc4a67ab91c2)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/71ee06d7-7767-43df-b3b1-9ebfdae752a4)

**Comment by bedauern** [comment]
<img width="855" alt="Snipaste_2023-05-24_20-46-59" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/fd541f97-6d6a-44eb-b7e2-d912b94b1642">

**Comment by foxbou** [comment]
<img width="976" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/5b8a9267-5109-4319-9e9a-cc3b1d47f2f2">

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/9ebe2230-8878-4419-b5fd-96dbddd3ca3d)

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/04c62aef-86b2-4bbf-8159-814e48dca81b)

**Comment by syr2212061031** [comment]
![4{IWZZ$V4N% 5O1J}VXI6)7](https://github.com/umdreamer/leetcodeproblems/assets/132579828/2aa7f954-29ed-4298-a37e-407bf74d27a9)

**Comment by 12baoxingyu-6** [comment]
<img width="755" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/d75e9a06-d7a3-4a30-9298-8e6be08cfbab">

**Comment by FXL1006** [comment]
<img width="235" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/c5867db4-11d3-47bb-a71e-418de4eb76b2">

**Comment by htywan** [comment]
![Uploading 11.png…]()

**Comment by htywan** [comment]
![11](https://github.com/umdreamer/leetcodeproblems/assets/132428178/022fc0da-69db-4d62-a1a3-41ab977b6646)

**Comment by shylieisme** [comment]
![8V6S3WK$GW``3GU3@)@J}PK](https://github.com/umdreamer/leetcodeproblems/assets/132582721/58d87492-f17b-4a5b-ae61-16cb0a830f1e)

**Comment by zyhzxy99** [comment]
![6`A5)3SFX629389C_HJSMKT](https://github.com/umdreamer/leetcodeproblems/assets/132050929/4ad63a49-99c3-4b19-86d0-9dac223b0305)

**Comment by gusuning** [comment]
<img width="937" alt="屏幕截图 2023-05-24 221020" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/6657eb81-9222-44c5-8084-8287ff8c8d54">

**Comment by 24zlx** [comment]
![联想截图_20230524221634](https://github.com/umdreamer/leetcodeproblems/assets/132560099/e700a7dc-d768-49c4-aacf-6e3c770db46d)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-24 22 33 03" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/c5f77992-757f-499c-b986-b0f56be61f5a">

**Comment by zangfushuo** [comment]
<img width="695" alt="截屏2023-05-24 22 39 27" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/2a61b803-9cbb-428b-a227-8a15a11e0155">
