### ISSUE TITLE
2023.05.25 Problem: 168. Excel Sheet Column Title

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#22]
168. Excel Sheet Column Title
[Problem Link](https://leetcode.cn/problems/excel-sheet-column-title/solutions/)

Given an integer columnNumber, return its corresponding column title as it appears in an Excel sheet.

For example:
```
A -> 1
B -> 2
C -> 3
...
Z -> 26
AA -> 27
AB -> 28 
...
``` 

Example 1:
```
Input: columnNumber = 1
Output: "A"
```
Example 2:
```
Input: columnNumber = 28
Output: "AB"
```
Example 3:
```
Input: columnNumber = 701
Output: "ZY"
``` 

Constraints:

* `1 <= columnNumber <= 231 - 1`

**Comment by zyhzxy99** [comment]
![I1 IAGZPWJX2~XV2JYJ@%Y7](https://github.com/umdreamer/leetcodeproblems/assets/132050929/76461818-5644-4b3a-9bc5-4ddb86ee6d47)

**Comment by daowuwu** [comment]
![REOHT@1WU03X2RQ 85W)JNO](https://github.com/umdreamer/leetcodeproblems/assets/132571490/dd522a83-fa61-4921-809f-9ba30322ac6d)

**Comment by tangyexi** [comment]
<img width="857" alt="屏幕截图 2023-05-25 172246" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/d847aaf8-212f-419f-b3d6-efe48cf45b10">

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/6056adf3-1c7a-4922-a83c-696793206241)

**Comment by syr2212061031** [comment]
![CNI5KULQG N7GL 8GUF1233](https://github.com/umdreamer/leetcodeproblems/assets/132579828/8110050f-06c0-415a-a165-5a12d939eadf)

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/be71dc0f-2843-439c-8716-24e0f0f7d6a3)

**Comment by mafanjia** [comment]
![截屏13](https://github.com/umdreamer/leetcodeproblems/assets/132454776/12c21da8-917f-4f2c-91ec-97abb866736a)

**Comment by cuixiao02** [comment]
<img width="644" alt="截屏2023-05-25 17 42 24" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/4453aac5-5ba9-460f-8c21-497af1b5a69b">

**Comment by PinkyLame** [comment]
![XDA G1)6(CS32MO2E42Y`EF](https://github.com/umdreamer/leetcodeproblems/assets/132571584/dace7d2a-6ea0-456a-9825-688f5ade8bfa)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/86141dba-6931-4c1b-8524-6a4e9ad1e2d4)

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/ef030c7a-d408-4db4-a2a1-442d88740562)

**Comment by foxbou** [comment]
<img width="977" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/267bed9b-a86d-465f-bbdd-28a74e88d94e">

**Comment by liu-si-han** [comment]
<img width="800" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/34deeecb-20bd-460b-8aba-d7105ead4094">

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/e4d76a99-831e-409a-a2ea-c6862e7f2b46)

**Comment by naqianqpg** [comment]
![1{XM6(8D7}%8%1V1}HAU JF](https://github.com/umdreamer/leetcodeproblems/assets/132567187/1925c214-9dab-4e83-a0f9-8a1cf3d5d1b4)

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/92964e68-5bd0-4219-a96f-8af49b6df9d0)

**Comment by gusuning** [comment]
![Uploading 屏幕截图 2023-05-25 190755.png…]()

**Comment by gusuning** [comment]
<img width="937" alt="屏幕截图 2023-05-25 190755" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/140d83f7-c2bc-4486-b94f-727e50a1da17">

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-25 181441](https://github.com/umdreamer/leetcodeproblems/assets/117709686/5d695361-5acb-4d80-bd79-a7cf6c5ac36a)

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/2de3c71c-20a7-4b66-87d6-58b57a5cf65d)

**Comment by 12baoxingyu-6** [comment]
<img width="821" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/f7d496dd-7fe0-4df9-800f-64f594c95ffb">

**Comment by huangyumei1** [comment]
![QQ图片20230525210233](https://github.com/umdreamer/leetcodeproblems/assets/122475924/5c7bad07-5644-46aa-9b8b-aa3df1e8fea5)

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/3f2691b0-3b08-45c5-bd75-e716187f12fa)

**Comment by 686xiaozhang** [comment]
![QQ截图20230525210653](https://github.com/umdreamer/leetcodeproblems/assets/132082348/9a27a0be-07dd-47e4-95f3-18c08200af19)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-25 21 07 46" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/510c35bc-35e5-49b7-a3af-ada06eee2559">

**Comment by 123lrb** [comment]
![}J490Y37U1_)THRC$LJUCHK](https://github.com/umdreamer/leetcodeproblems/assets/132526491/9fa42134-ebcd-49ea-8b2e-b45364a10a56)

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/361c0954-ba5f-4f79-8049-6aeb8520c1d4)

**Comment by htywan** [comment]
![1](https://github.com/umdreamer/leetcodeproblems/assets/132428178/204a4f9f-42e0-4d2b-a5b0-eda214d9e178)

**Comment by bedauern** [comment]
<img width="811" alt="Snipaste_2023-05-25_21-24-45" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/57d799d0-33ee-48cd-b32b-da0f96219c65">

**Comment by FXL1006** [comment]
<img width="811" alt="屏幕截图 2023-05-23 200824" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/4cbd2a72-8d53-4714-8732-1e901da5ec9e">

**Comment by 24zlx** [comment]
![联想截图_20230525212748](https://github.com/umdreamer/leetcodeproblems/assets/132560099/ad419620-a748-48c5-a4c5-936b1646311d)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/dc27866c-39da-4335-bb68-c8cb11aee8ac)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/dc27866c-39da-4335-bb68-c8cb11aee8ac)
