### ISSUE TITLE
2023.05.26 Problem:  566. Reshape the Matrix

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#23]
566. Reshape the Matrix
[Problem Link](https://leetcode.cn/problems/reshape-the-matrix/)

In MATLAB, there is a handy function called reshape which can reshape an m x n matrix into a new one with a different size r x c keeping its original data.

You are given an m x n matrix mat and two integers r and c representing the number of rows and the number of columns of the wanted reshaped matrix.

The reshaped matrix should be filled with all the elements of the original matrix in the same row-traversing order as they were.

If the reshape operation with given parameters is possible and legal, output the new reshaped matrix; Otherwise, output the original matrix.

Example 1:
![image](https://github.com/umdreamer/leetcodeproblems/assets/15782682/5dcef4a1-8587-4a18-a48a-79f9c5d62874)

```
Input: mat = [[1,2],[3,4]], r = 1, c = 4
Output: [[1,2,3,4]]
```
Example 2:
![image](https://github.com/umdreamer/leetcodeproblems/assets/15782682/df9300d1-2e40-4ba9-9a3a-82d968ebecb6)

```
Input: mat = [[1,2],[3,4]], r = 2, c = 4
Output: [[1,2],[3,4]]
``` 

Constraints:

* `m == mat.length`
* `n == mat[i].length`
* `1 <= m, n <= 100`
* `-1000 <= mat[i][j] <= 1000`
* `1 <= r, c <= 300`

**Comment by tangyexi** [comment]
<img width="936" alt="屏幕截图 2023-05-26 221229" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/80acbb55-5674-4e56-9e8b-7b3be7aa571f">

**Comment by liu-si-han** [comment]
<img width="776" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/a88bd731-a068-4689-a1f1-4c0089ff2406">

**Comment by huangyumei1** [comment]
![QQ图片20230526221806](https://github.com/umdreamer/leetcodeproblems/assets/122475924/f22ae6da-d970-4dbf-88ec-8f1187885c11)

**Comment by htywan** [comment]
![111](https://github.com/umdreamer/leetcodeproblems/assets/132428178/81ad37eb-8342-4ddb-92b2-aecb0abcdba7)

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/e1448f74-ed7b-405d-ba24-0bd5d2e8380d)

**Comment by 686xiaozhang** [comment]
![QQ截图20230526233619](https://github.com/umdreamer/leetcodeproblems/assets/132082348/15624a15-2649-4cd0-98e0-452b71f78239)

**Comment by naqianqpg** [comment]
![Z{W 9P)_8D PE7)7D0 (P4T](https://github.com/umdreamer/leetcodeproblems/assets/132567187/61680210-4be6-4172-887e-126579284f84)

**Comment by mafanjia** [comment]
![截屏14](https://github.com/umdreamer/leetcodeproblems/assets/132454776/7b5a5cd2-106c-4ee3-9584-82a43bd30e21)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-27 115858](https://github.com/umdreamer/leetcodeproblems/assets/117709686/f7e550aa-a04e-4c9d-b6da-e6e6bb8f9284)

**Comment by 123lrb** [comment]
![TK%K5 `@{9PFWZ6F)OO2LRV](https://github.com/umdreamer/leetcodeproblems/assets/132526491/93ef2a17-45e8-4925-a432-1730b90681aa)

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/6ff9de51-5854-4a7e-850a-237ea1331bb4)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/43ab3fce-9ce0-485f-82ec-0d0139dcc5f3)

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/82726d17-1eeb-46a7-8ab8-324c3fb073f5)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-27 14 10 23" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/edbf238c-f2f8-4c1e-b07e-3bd9ba500304">

**Comment by zyhzxy99** [comment]
![O 8`S QNZGL NWFVY@ GKSQ](https://github.com/umdreamer/leetcodeproblems/assets/132050929/2b1bec10-ccda-4527-96bf-54c11a6294f8)

**Comment by syr2212061031** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132579828/cfaffbf9-88a3-4ff1-a851-ecf755815389)

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/5fa394d9-af3c-44f5-a63b-99175543c9df)

**Comment by foxbou** [comment]
<img width="900" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/c5d620f2-a2be-45c3-80a7-c46118ef2062">

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/dc6c3471-ad96-41f7-94f0-e3b6cb5ebdd6)

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/ecae9e80-6aac-4c75-8c73-1aaa0d256120)

**Comment by FXL1006** [comment]
<img width="793" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/1f9b8d1c-0e2a-4dac-bc6f-63020524a6b4">

**Comment by daowuwu** [comment]
![IHD68B5_%R%{Z6T$1))R6Z6](https://github.com/umdreamer/leetcodeproblems/assets/132571490/3bf80c9a-7479-430d-b4ba-dc584220e194)

**Comment by 12baoxingyu-6** [comment]
<img width="729" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/cb24d9d7-92d1-4942-bca6-b1c882d536e6">

**Comment by 24zlx** [comment]
![联想截图_20230527165629](https://github.com/umdreamer/leetcodeproblems/assets/132560099/ece886c8-6dc3-4f17-a443-ebbf7aacc748)

**Comment by bedauern** [comment]
<img width="800" alt="Snipaste_2023-05-27_17-14-37" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/8497501f-80bc-42d9-9c15-149e671d8389">

**Comment by gusuning** [comment]
<img width="757" alt="屏幕截图 2023-05-27 172708" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/c102909f-802c-49da-9b20-86abc1b40d74">

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/81edaea7-7f41-4047-8662-4d17000cbbbe)

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/48c16401-f46e-4f4c-8d42-1cdbe9ec53ea)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/1d917a9e-fdad-4fad-99bf-587021af4b32)

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/f5a81a11-068c-4a73-8476-a9bd8871fdab)

**Comment by shylieisme** [comment]
![J7S~ WD@AS01Z JS_AM~8)M](https://github.com/umdreamer/leetcodeproblems/assets/132582721/5280635f-d940-43b2-9595-71dbc9c41262)

**Comment by zangfushuo** [comment]
<img width="691" alt="截屏2023-05-27 22 43 03" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/9aca8cbc-cbe1-435c-842d-2a8b2413b925">

**Comment by cuixiao02** [comment]
![IMG_2111](https://github.com/umdreamer/leetcodeproblems/assets/132454083/dd9b75d4-d8ec-4bb1-b083-021d6ff1cdff)
