### ISSUE TITLE
2023.05.27 Problem: 202. Happy Number

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#24]
202. Happy Number
[Problem Link](https://leetcode.cn/problems/happy-number/)

Write an algorithm to determine if a number n is happy.

A happy number is a number defined by the following process:

Starting with any positive integer, replace the number by the sum of the squares of its digits.
Repeat the process until the number equals 1 (where it will stay), or it loops endlessly in a cycle which does not include 1.
Those numbers for which this process ends in 1 are happy.
Return true if n is a happy number, and false if not.

Example 1:
```
Input: n = 19
Output: true
Explanation:
12 + 92 = 82
82 + 22 = 68
62 + 82 = 100
12 + 02 + 02 = 1
```

Example 2:
```
Input: n = 2
Output: false
``` 

Constraints:
* `1 <= n <= 231 - 1`

**Comment by zhjingyan** [comment]
![屏幕截图 2023-05-27 151939](https://github.com/umdreamer/leetcodeproblems/assets/132195009/cd8f3a4b-a1d5-41ad-af6f-efdb2226da98)

**Comment by foxbou** [comment]
<img width="873" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/5dd0a207-22ff-49bf-8441-e9b4dade3a6a">

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-27 160538](https://github.com/umdreamer/leetcodeproblems/assets/117709686/fdc502ce-029c-4a5d-907f-fe4e6f3f89ec)

**Comment by daowuwu** [comment]
![AE49@81 3F0`ZIT(B%CTYCO](https://github.com/umdreamer/leetcodeproblems/assets/132571490/ddca1971-c350-4b77-9c0d-bbd6fc2e1752)

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/1c31ab40-970a-4d75-be93-70de77a16433)

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/31b2bc2a-7294-436f-8410-edfe85485fff)

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/28d82f61-4ffc-4a56-81ec-b44d062e1b1b)

**Comment by tangyexi** [comment]
<img width="905" alt="屏幕截图 2023-05-27 171525" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/cf79e854-1e50-4d53-96d5-45bed731cdd1">

**Comment by bedauern** [comment]
<img width="793" alt="Snipaste_2023-05-27_17-15-39" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/36661772-b918-4dfe-9d86-80c1955ae113">

**Comment by liu-si-han** [comment]
<img width="793" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/1f21299b-c33b-4b6f-9117-e274a921a4ba">

**Comment by huangyumei1** [comment]
![QQ图片20230527172824](https://github.com/umdreamer/leetcodeproblems/assets/122475924/9693bb94-5bc9-4b3c-9445-bbff14c301c6)

**Comment by mafanjia** [comment]
![截屏15](https://github.com/umdreamer/leetcodeproblems/assets/132454776/a6848e06-6209-4179-ba4d-94e952a7a601)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-27 18 19 55" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/b000d3d6-4b1e-4b71-a6d0-89e6d64932ad">

**Comment by gusuning** [comment]
<img width="943" alt="屏幕截图 2023-05-27 191942" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/765d880d-8962-41de-aedc-fb48eec6b951">

**Comment by syr2212061031** [comment]
![1@P9_ZR@YTX$MXH{FB)~}81](https://github.com/umdreamer/leetcodeproblems/assets/132579828/9c223953-875f-4604-b89b-05d3be05658a)

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/1958b96c-e8d7-4580-88c1-cdb19a339491)

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/9770e4af-4c80-4cc1-895e-3cbb527f4d83)

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/fa69d223-272f-4cdd-bc05-b60232d3e971)

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/d3f6a57a-e97e-456e-9a95-76917321b90a)

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/9a78db76-7cd5-484b-850d-171deeb259a8)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/cc7d03e4-5ff0-4160-85db-15756685ec02)

**Comment by 123lrb** [comment]
![MU@`VD2X8D O8{I~ZAEQC`D](https://github.com/umdreamer/leetcodeproblems/assets/132526491/0c12fe4e-c559-4655-8a27-3e29a58d706d)

**Comment by 686xiaozhang** [comment]
![QQ截图20230527213621](https://github.com/umdreamer/leetcodeproblems/assets/132082348/00a06c17-b276-49b2-be13-12fc75324638)

**Comment by FXL1006** [comment]
<img width="828" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/a3e17ee7-1fad-46cf-a537-7c151ed1aeff">

**Comment by 24zlx** [comment]
![联想截图_20230527165945](https://github.com/umdreamer/leetcodeproblems/assets/132560099/4379f5f2-a0f5-47eb-a9c5-626ca1edb2e5)

**Comment by naqianqpg** [comment]
![8%8Y6ULLOXX $G4S `{3TFE](https://github.com/umdreamer/leetcodeproblems/assets/132567187/da93ec64-2654-4133-8aa4-3d35bcabf8b2)

**Comment by htywan** [comment]
![111](https://github.com/umdreamer/leetcodeproblems/assets/132428178/85dce7eb-2a59-411b-ba8b-34041608cb08)

**Comment by zyhzxy99** [comment]
![C48KQ9C~$@)(DK_MBAK1G5C](https://github.com/umdreamer/leetcodeproblems/assets/132050929/0ee73353-154e-4800-acdc-102cb49a3b7c)

**Comment by 12baoxingyu-6** [comment]
<img width="790" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/9a7558a8-ca35-4d11-87a2-daaf6151f4fb">

**Comment by shylieisme** [comment]
![8T1`RN{FFFZR9@DSQYA43OW](https://github.com/umdreamer/leetcodeproblems/assets/132582721/1a336ee3-928d-4513-b8ff-430b4816ac5a)

**Comment by zangfushuo** [comment]
<img width="677" alt="截屏2023-05-27 22 36 35" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/21879bf9-b449-4088-8f58-8367cbc48487">

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/ff97b3e2-4319-49a5-9446-44e9c168f753)

**Comment by cuixiao02** [comment]
![IMG_2112](https://github.com/umdreamer/leetcodeproblems/assets/132454083/cdc30580-f014-42c1-b637-82bf14df5ed2)
