### ISSUE TITLE
2023.05.29 Problem 263. Ugly Number

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#25]
263. Ugly Number
[Problem Link](https://leetcode.cn/problems/ugly-number/)
An ugly number is a positive integer whose prime factors are limited to 2, 3, and 5.

Given an integer n, return true if n is an ugly number.

 
Example 1:
```
Input: n = 6
Output: true
Explanation: 6 = 2 × 3
```
Example 2:
```
Input: n = 1
Output: true
Explanation: 1 has no prime factors, therefore all of its prime factors are limited to 2, 3, and 5.
```
Example 3:
```
Input: n = 14
Output: false
Explanation: 14 is not ugly since it includes the prime factor 7.
``` 

Constraints:

* `-231 <= n <= 231 - 1`

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-29 122034](https://github.com/umdreamer/leetcodeproblems/assets/117709686/0e6bd06b-9486-4959-8738-f5e61bfb5888)

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/afcb23ad-74a6-4af0-94f5-84932bf548ed)

**Comment by liu-si-han** [comment]
<img width="785" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/a6501974-15d3-4768-9876-3bddf600667b">

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/9b31b958-b422-45e5-a098-0f9164aaf739)

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/54b0a061-74c6-4c33-9242-2446422a582c)

**Comment by tangyexi** [comment]
<img width="950" alt="屏幕截图 2023-05-29 161011" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/2d639905-518b-4e01-ac0f-4fe24ecf3d46">

**Comment by FXL1006** [comment]
<img width="80" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/c94ec8bb-d122-4da2-b4ea-ff0e8430fe3f">

**Comment by FXL1006** [comment]
<img width="812" alt="屏幕截图 2023-05-29 163517" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/6a27bd90-08e9-4fac-b802-cb632395d378">

**Comment by gusuning** [comment]
<img width="931" alt="屏幕截图 2023-05-29 170945" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/26066f3b-1551-40c4-a6b4-c0f8718672ec">

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/93593898-560b-48fe-a5df-5245afef3d75)

**Comment by daowuwu** [comment]
![RS~C QXKPLXSXY7`(NZVK19](https://github.com/umdreamer/leetcodeproblems/assets/132571490/d5aa61fc-e9ae-4364-abc1-9955fb0318af)

**Comment by zyhzxy99** [comment]
![YIMZ}{KT4BB@M9F4 RQJ9FQ](https://github.com/umdreamer/leetcodeproblems/assets/132050929/983fb5ee-479c-46cb-a6e6-7548dc9bab45)

**Comment by bedauern** [comment]
<img width="763" alt="Snipaste_2023-05-29_17-36-13" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/0139c6c7-52b8-43fc-8972-1366f5051d41">

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/f8e2018b-11ef-4ad2-8e42-9399dfe0a876)

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/aa3205b7-f049-40f0-acfd-0a0e41e56687)

**Comment by 12baoxingyu-6** [comment]
<img width="763" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/89891de5-2236-4b1f-b8f2-e4cf4288a1a4">

**Comment by syr2212061031** [comment]
![B(}VHJC@C8_XI@T%ESMNI0A](https://github.com/umdreamer/leetcodeproblems/assets/132579828/3c65bf14-ec1a-4218-902f-d03c03879f60)

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/f8c3fb9f-36d6-4a91-8c82-d392da0a9860)

**Comment by 686xiaozhang** [comment]
![QQ截图20230529203843](https://github.com/umdreamer/leetcodeproblems/assets/132082348/563f8747-2006-437e-b3b0-7c5fd84be98c)

**Comment by 123lrb** [comment]
![J~E9BR5E7 2Z{7 T6@0Z2](https://github.com/umdreamer/leetcodeproblems/assets/132526491/ca18e5d0-0d5a-4906-8c69-360b19e5dfdc)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/43655eb1-2991-4b6b-8d18-e2728cb36c82)

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/942661e7-165e-464e-b29a-31fc28d97be4)

**Comment by huangyumei1** [comment]
![QQ图片20230529205025](https://github.com/umdreamer/leetcodeproblems/assets/122475924/e7524cb6-b17a-4a81-a6af-baf475e8fb7e)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/72faa1ed-e8ca-4732-97b0-6bdccdfe49a0)

**Comment by naqianqpg** [comment]
![S(_`5C%_PT(`E((JPJ}90](https://github.com/umdreamer/leetcodeproblems/assets/132567187/d5556ed9-ffcd-4744-9618-4482c86ccd03)

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/b30dd5ee-9383-449d-abcd-0c1e68a433d9)

**Comment by mafanjia** [comment]
![截屏16](https://github.com/umdreamer/leetcodeproblems/assets/132454776/9dc06495-9d6c-4911-a037-a7ccf7e20de9)

**Comment by 24zlx** [comment]
![联想截图_20230529215405](https://github.com/umdreamer/leetcodeproblems/assets/132560099/972658aa-7482-4ab9-b43c-fb200fdce956)

**Comment by htywan** [comment]
![1](https://github.com/umdreamer/leetcodeproblems/assets/132428178/b23764d7-dd4c-470d-b2c3-a0ea6f17dfd7)

**Comment by cuixiao02** [comment]
<img width="628" alt="截屏2023-05-29 23 02 47" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/8fac4758-e204-4ce2-ab98-87e95f015487">

**Comment by foxbou** [comment]
<img width="878" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/e52ea83f-e924-453a-8b70-54669dbc7333">

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-30 20 46 22" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/0c5c7010-ef6f-4643-b191-41c0f0c8a3d1">

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/fd0ca811-6498-4aa8-b704-3a02281c94a5)
