### ISSUE TITLE
2023.5.30 Problem: 100. Same Tree

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#26]
100. Same Tree
[Problem Link](https://leetcode.cn/problems/same-tree/)

Given the roots of two binary trees p and q, write a function to check if they are the same or not.

Two binary trees are considered the same if they are structurally identical, and the nodes have the same value.

 

Example 1:
![image](https://github.com/umdreamer/leetcodeproblems/assets/15782682/ad3c4d6f-63a7-44a0-8d29-15ef4c95c8ca)

```
Input: p = [1,2,3], q = [1,2,3]
Output: true
```
Example 2:
![image](https://github.com/umdreamer/leetcodeproblems/assets/15782682/bd7fd38a-c255-49dd-8bfc-a8a55ec71bb6)

```
Input: p = [1,2], q = [1,null,2]
Output: false
```
Example 3:
![image](https://github.com/umdreamer/leetcodeproblems/assets/15782682/090f0a6c-8aac-4307-8655-91a605bc6f99)

```
Input: p = [1,2,1], q = [1,1,2]
Output: false
``` 

Constraints:

* `The number of nodes in both trees is in the range [0, 100].`
* `-104 <= Node.val <= 104`

**Comment by tangyexi** [comment]
<img width="885" alt="屏幕截图 2023-05-30 210127" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/c7d4b92c-e945-4687-8bf0-0667a3fba696">

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/ad66e929-f485-46d3-843f-401c87b44eab)

**Comment by huangyumei1** [comment]
![QQ图片20230530213127](https://github.com/umdreamer/leetcodeproblems/assets/122475924/14414fa9-d1cd-4134-a20e-e6b58255e19d)

**Comment by htywan** [comment]
![1](https://github.com/umdreamer/leetcodeproblems/assets/132428178/bd1f22a6-0502-4a2d-bd3e-f881e5deff6a)

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/791b099f-27e2-481b-a43d-91a471c543ee)

**Comment by cuixiao02** [comment]
<img width="610" alt="截屏2023-05-31 11 58 43" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/bdc27df6-340c-4a01-9d2c-d914a9695362">

**Comment by gusuning** [comment]
![Uploading 屏幕截图 2023-05-31 143939.png…]()

**Comment by gusuning** [comment]
<img width="916" alt="屏幕截图 2023-05-31 143939" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/cd19a37d-8db6-406a-b925-ab2a83fafe0d">

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/4e8a87ba-5af1-479e-bd45-5bfdd4fa081a)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-30 210327](https://github.com/umdreamer/leetcodeproblems/assets/117709686/897036e5-d3fc-4dc4-9ffc-05b07adac59a)

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/b75eebc8-e444-418f-bc3b-29cf42d434e0)

**Comment by mafanjia** [comment]
![截屏100](https://github.com/umdreamer/leetcodeproblems/assets/132454776/e889e9ba-b885-4307-b899-e0a7540e746e)

**Comment by 123lrb** [comment]
![_G71OFK9PL0ZQ C4HA2P34K](https://github.com/umdreamer/leetcodeproblems/assets/132526491/a9ebac2e-7344-41dd-a4a0-5f272292999c)

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/afe32b6f-bb55-4136-ac08-1bbccee64ceb)

**Comment by 12baoxingyu-6** [comment]
<img width="805" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/18e1decb-b541-43e8-8c74-47d5db1cffa0">

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/ded508eb-9021-4f5c-b72e-ae7a89ab2084)

**Comment by liu-si-han** [comment]
<img width="776" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/8e4f1e2d-06d5-4044-b5b2-72645d6a1e68">

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/ec8c70c6-dc5a-471b-94dc-c21be559868a)

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/3a82b3b1-3be2-4521-bc5d-9195e816c31c)

**Comment by syr2212061031** [comment]
![07XQ2Y)53U(4@@@E@$94H@9](https://github.com/umdreamer/leetcodeproblems/assets/132579828/db8a4b25-d91e-4d20-9901-ab6fe149bfab)

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/5dc75b01-0ea7-49fc-99d0-cfda43322ccc)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/c2b00c98-5062-437b-94f2-28e583524714)

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/7a3fcb00-50ea-4684-a937-ff52f3f70d8a)

**Comment by 24zlx** [comment]
![联想截图_20230531211429](https://github.com/umdreamer/leetcodeproblems/assets/132560099/ba8a7401-3889-46ac-b3d6-9e69a9e1ed25)

**Comment by naqianqpg** [comment]
![H023ED57Z`O~QFXSCDB44GY](https://github.com/umdreamer/leetcodeproblems/assets/132567187/2dff9fad-0608-4952-a359-660bc8804f40)

**Comment by daowuwu** [comment]
![O_C)T~28VFNB G7$KS24WYO](https://github.com/umdreamer/leetcodeproblems/assets/132571490/31ac903f-1a4a-4744-a145-69d567fe69a6)

**Comment by zyhzxy99** [comment]
![L7YNF$5S9`2RYQ)5EN72CF0](https://github.com/umdreamer/leetcodeproblems/assets/132050929/03163c74-9d0a-4d56-8160-b5da426a19d0)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-30 20 46 22" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/4fce011f-671a-4c7c-a263-4448315f6fcf">

**Comment by bedauern** [comment]
<img width="801" alt="Snipaste_2023-05-31_22-16-53" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/bfe81dfc-1739-4674-af3c-5a784deb4151">

**Comment by foxbou** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526020/f3c179a7-fac1-4f3c-a466-487e17a4db60)

**Comment by zangfushuo** [comment]
<img width="682" alt="截屏2023-05-31 23 31 36" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/c838f279-1795-4be7-adfb-b7f7e8dc4bde">

**Comment by shylieisme** [comment]
![X@GS3%JTWXN %L2S I67EJN](https://github.com/umdreamer/leetcodeproblems/assets/132582721/32df51fd-7090-425b-9f68-2dcd7c8522c7)

**Comment by 686xiaozhang** [comment]
![QQ截图20230601173847](https://github.com/umdreamer/leetcodeproblems/assets/132082348/7c3d5928-6459-4500-a432-dd8954d9e7f6)
