### ISSUE TITLE
2023.05.31 Problem: 217. Contains Duplicate

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#27]
217. Contains Duplicate
[Problem Link](https://leetcode.cn/problems/contains-duplicate/)

Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.

 

Example 1:
```
Input: nums = [1,2,3,1]
Output: true
```
Example 2:
```
Input: nums = [1,2,3,4]
Output: false
```
Example 3:
```
Input: nums = [1,1,1,3,3,4,3,2,4,2]
Output: true
``` 

Constraints:

* `1 <= nums.length <= 105`
* `-109 <= nums[i] <= 109`

**Comment by cuixiao02** [comment]
<img width="636" alt="截屏2023-05-31 12 00 26" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/b544c564-29d0-4b67-9e7e-d6665b300a9a">

**Comment by tangyexi** [comment]
<img width="791" alt="屏幕截图 2023-05-31 123549" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/d3b6342b-c13e-4f22-b9dc-37c1b7f9cbf4">

**Comment by gusuning** [comment]
<img width="889" alt="屏幕截图 2023-05-31 144104" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/df43f867-b62f-4516-90bb-13c5ef4c7083">

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/40f0ea99-93b2-4da8-80e0-be1eb390c2d7)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-31 171556](https://github.com/umdreamer/leetcodeproblems/assets/117709686/87c0f68a-c943-45b5-a99f-f66f034ff475)

**Comment by mafanjia** [comment]
![截屏217](https://github.com/umdreamer/leetcodeproblems/assets/132454776/2c3ab5c7-308b-49b7-bac0-a6a72efe71f2)

**Comment by 123lrb** [comment]
![SMA6$WHWB L3}950XRH$@FM](https://github.com/umdreamer/leetcodeproblems/assets/132526491/3d094373-e2d3-48e7-b028-e0383906c36d)

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/186cde8b-4f5a-42b7-b531-11c072de9bd3)

**Comment by 12baoxingyu-6** [comment]
<img width="770" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/24ef623a-f2e7-49b8-baa7-b8acffac02bf">

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/b6283adc-1794-4277-b591-5fac6991520d)

**Comment by liu-si-han** [comment]
<img width="805" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/33fb979a-7fbb-4fac-8b7f-5811e729534c">

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/70d7ec78-a4e7-497d-ba30-636ac6224ff2)

**Comment by huangyumei1** [comment]
![QQ图片20230531203533](https://github.com/umdreamer/leetcodeproblems/assets/122475924/eba6553d-7536-4a8d-842f-4d1fad0dda02)

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/a6f207da-99b4-455e-b797-fd0f294cc3c3)

**Comment by syr2212061031** [comment]
![FCEUX6BT9V4VT@$}7X 1~IQ](https://github.com/umdreamer/leetcodeproblems/assets/132579828/23312ee7-6cb6-4a04-a744-da992b659a20)

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/dfe1be11-89dd-4cf3-beeb-a90980b3d91e)

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/a525cd7f-1f00-4596-bc0d-e2bfaa264938)

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/ca9f7d75-54bb-4370-b880-d85902c33e06)

**Comment by 24zlx** [comment]
![联想截图_20230531205951](https://github.com/umdreamer/leetcodeproblems/assets/132560099/593f23e0-ef8c-4d99-a26e-758b97366f9e)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/ad8af4b1-27f3-4343-a3f1-9e4534f1b11c)

**Comment by promisewith7** [comment]
<img width="639" alt="联想截图_20230531211312" src="https://github.com/umdreamer/leetcodeproblems/assets/132559311/c6edcb33-f412-4cac-ac06-16f4d4e0fe09">

**Comment by htywan** [comment]
![1](https://github.com/umdreamer/leetcodeproblems/assets/132428178/d38b3f5e-e7c0-4135-b016-b7e93ad27fae)

**Comment by naqianqpg** [comment]
![1UEY`5E1_`VA}XAVEF)3Q2C](https://github.com/umdreamer/leetcodeproblems/assets/132567187/b39c76f1-385c-4951-b1db-177e04595c03)

**Comment by 686xiaozhang** [comment]
![QQ截图20230531214938](https://github.com/umdreamer/leetcodeproblems/assets/132082348/3275f912-e1f6-4095-a008-89d6db0f92f7)

**Comment by daowuwu** [comment]
![XL{2F@I@(`D ARX2MCIFU2](https://github.com/umdreamer/leetcodeproblems/assets/132571490/89ae2400-c43f-4bef-aa63-d033a2e2980d)

**Comment by zyhzxy99** [comment]
![Q0N0ND5{`L6 G)}U5C)Y7SW](https://github.com/umdreamer/leetcodeproblems/assets/132050929/63860034-8f8f-4e1c-8682-e225f2979b24)

**Comment by FXL1006** [comment]
<img width="882" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/7867baa2-71b0-4fd4-95f7-f6d7b3323f69">

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-31 22 14 34" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/3b7e02c3-93ae-42a8-ad77-7c1be377a78a">

**Comment by bedauern** [comment]
<img width="799" alt="Snipaste_2023-05-31_22-17-42" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/2a211dd8-4a4b-446e-858b-8f47f76b9c95">

**Comment by foxbou** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526020/191dd5bc-3da8-4d23-a729-200c8130fcca)

**Comment by foxbou** [comment]
<img width="842" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/c3ac60f2-b0a4-4479-8460-4505bdd6d3aa">

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/9580b6e2-9b29-4dca-be94-22e5d7211873)

**Comment by shylieisme** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132582721/e0b7e06b-7aa8-4f7e-b00a-8312d3776071)

**Comment by zangfushuo** [comment]
<img width="670" alt="截屏2023-05-31 23 30 00" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/c87da192-cdd4-4903-8001-bcbf65f29e05">

**Comment by zangfushuo** [comment]
<img width="681" alt="截屏2023-06-01 20 49 44" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/dab6b5c5-0708-450d-bbe0-c15661639e0d">
