### ISSUE TITLE
2023.6.1 Problem: 144. Binary Tree Preorder Traversal

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#28]
144. Binary Tree Preorder Traversal
[Problem Link](https://leetcode.cn/problems/binary-tree-preorder-traversal/)

Given the root of a binary tree, return the preorder traversal of its nodes' values.

 

Example 1:
![image](https://github.com/umdreamer/leetcodeproblems/assets/15782682/77ea2e5c-8ee5-468a-9e02-8710fffaed9e)

```
Input: root = [1,null,2,3]
Output: [1,2,3]
```
Example 2:
```
Input: root = []
Output: []
```
Example 3:
```
Input: root = [1]
Output: [1]
``` 

Constraints:

* The number of nodes in the tree is in the range `[0, 100].`
* `-100 <= Node.val <= 100`

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/092f3d84-0ad1-494b-a9ea-f358a38edcec)

**Comment by bedauern** [comment]
<img width="808" alt="Snipaste_2023-06-01_15-45-15" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/e6bf80bf-b281-4e86-9ba8-b5468780a7d1">

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-06-01 16 54 37" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/33a14fe6-0d67-40b8-aec1-9e20e744736f">

**Comment by tangyexi** [comment]
<img width="823" alt="屏幕截图 2023-06-01 165847" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/ce500edd-ffd6-4b0d-aa01-634ea3a40286">

**Comment by liu-si-han** [comment]
<img width="795" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/dd11e915-86a4-4f10-a806-2b13932f8c25">

**Comment by daowuwu** [comment]
![H $T`HSAO)@A0S$RY21J 44](https://github.com/umdreamer/leetcodeproblems/assets/132571490/a273f32c-48f5-4d42-9264-0bd3eb376309)

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/0ea5e3e4-fea9-4a2e-96ec-c799f8bfc095)

**Comment by mafanjia** [comment]
![截屏144](https://github.com/umdreamer/leetcodeproblems/assets/132454776/3a1dde30-f2b9-4527-8e80-d157edec9399)

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/03c0bf34-c6f9-49f1-b3eb-1b2b839816ce)

**Comment by 686xiaozhang** [comment]
![ii那天](https://github.com/umdreamer/leetcodeproblems/assets/132082348/38bfbece-dbfd-40fd-af71-785ccec16835)

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/627e5142-dc67-4cfe-9ba1-d84723d9afd8)

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/7fbc5c6a-8fdf-4f83-b4db-3ade92bdda78)

**Comment by syr2212061031** [comment]
![PPW%3D42RVFN0ND@YLHG3F8](https://github.com/umdreamer/leetcodeproblems/assets/132579828/c65d0d74-6296-47fc-ae6f-1054f5bd7f43)

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/c50cb499-de8e-4c20-a2d4-f8e705336b9e)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/011ce75c-26f9-4be2-8630-a1a0528a75b3)

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/5585b325-b16f-4a5c-94a2-e07972e1abce)

**Comment by zyhzxy99** [comment]
![NA JO2IPG}AF{SB}I_P(MQ](https://github.com/umdreamer/leetcodeproblems/assets/132050929/790ec901-a9fe-4bd6-83a2-46849f5ddbb1)

**Comment by huangyumei1** [comment]
![QQ图片20230601200439](https://github.com/umdreamer/leetcodeproblems/assets/122475924/fd72bbd3-50ea-4c3b-bd0d-61a5393094ca)

**Comment by 12baoxingyu-6** [comment]
<img width="773" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/cded57c0-3cb0-405c-b04a-c96b46f591d2">

**Comment by Lggg1234** [comment]
![屏幕截图 2023-06-01 203855](https://github.com/umdreamer/leetcodeproblems/assets/117709686/c8562c42-b840-4a2f-b308-3823070908a9)

**Comment by cuixiao02** [comment]
<img width="637" alt="截屏2023-06-01 20 41 34" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/aa2a42d2-2260-460e-976c-b7f794928717">

**Comment by 123lrb** [comment]
![YB9Q5J_NZILAV6P`_RL)N63](https://github.com/umdreamer/leetcodeproblems/assets/132526491/d825cc2c-7c16-48ab-9547-6a616b29d180)

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/2ec26231-6ad7-47e7-81e3-c9be20f4fd4c)

**Comment by FXL1006** [comment]
<img width="873" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/6da42e56-4c9d-4551-be44-2301a1d7fb17">

**Comment by gusuning** [comment]
<img width="944" alt="屏幕截图 2023-06-01 210436" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/918292ff-4f42-4265-b32b-37f8cc120211">

**Comment by htywan** [comment]
![QQ截图20230601211018](https://github.com/umdreamer/leetcodeproblems/assets/132428178/fb0e59cc-28ff-4d75-8620-7c1bb796cbb4)

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/a043028d-e83d-4724-ad43-7f24966601dc)

**Comment by naqianqpg** [comment]
![KDT8GIA0 FORCHEQX21YFID](https://github.com/umdreamer/leetcodeproblems/assets/132567187/becc208b-c46a-4887-b7fb-8930da32c74a)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/d6c19ca1-08e5-441e-8bc1-76dbd42a24c4)

**Comment by 24zlx** [comment]
![联想截图_20230601224817](https://github.com/umdreamer/leetcodeproblems/assets/132560099/0625ea23-733d-4e60-998a-6a1d5924970d)

**Comment by shylieisme** [comment]
![I0NF{MLC$ L(K2E VFQPS(D](https://github.com/umdreamer/leetcodeproblems/assets/132582721/62cad518-885f-414f-bfc2-14cdcaf8a99c)

**Comment by zangfushuo** [comment]
<img width="681" alt="截屏2023-06-01 20 49 44" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/d568b862-fbe7-489b-be40-437e2edbcb73">

**Comment by foxbou** [comment]
<img width="893" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/dcd50037-45c5-4de1-85c3-65a24c28e97b">
