### ISSUE TITLE
2023.6.2 Problem: 145. Binary Tree Postorder Traversal

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#29]
145. Binary Tree Postorder Traversal
[Problem Link](https://leetcode.cn/problems/binary-tree-postorder-traversal/)

Given the root of a binary tree, return the postorder traversal of its nodes' values.

 

Example 1:
![image](https://github.com/umdreamer/leetcodeproblems/assets/15782682/c0c68d39-0061-46f6-9def-7d934ff08d29)

```
Input: root = [1,null,2,3]
Output: [3,2,1]
```
Example 2:
```
Input: root = []
Output: []
```
Example 3:
```
Input: root = [1]
Output: [1]
``` 

Constraints:

* The number of the nodes in the tree is in the range `[0, 100]`.
* `-100 <= Node.val <= 100`

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/edd099c6-c2e3-4ab2-aa95-0fc25de7e7c1)

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/c8da4b19-8f37-4417-b949-b25689378241)

**Comment by FXL1006** [comment]
<img width="884" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/d04366ef-2a27-4248-8df1-cf845b9e4e77">

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/677fdd89-0c43-4a08-8f96-ecc4ddd0282e)

**Comment by 24zlx** [comment]
![联想截图_20230602172038](https://github.com/umdreamer/leetcodeproblems/assets/132560099/6443c3fb-7431-42fc-9b5e-2705355fccb4)

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/10989953-f5de-4d7d-b755-73021cbd078f)

**Comment by cuixiao02** [comment]
<img width="626" alt="截屏2023-06-02 17 32 01" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/82ea9c93-e601-4661-8b15-8d40b017a608">

**Comment by tangyexi** [comment]
<img width="826" alt="屏幕截图 2023-06-02 173400" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/7fc75a92-ce62-4ec6-9d57-841c3fc5ae4a">

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/17c493e5-7401-4144-8e31-ac122090db78)

**Comment by 12baoxingyu-6** [comment]
<img width="735" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/889a5e98-a8c9-4db7-8bd0-7c340b949480">

**Comment by mafanjia** [comment]
![截屏146](https://github.com/umdreamer/leetcodeproblems/assets/132454776/bd2482f7-a2f1-48e2-858f-8756e106e23a)

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/aa85b9ec-5000-4b7c-9182-9c7293188ae8)

**Comment by gusuning** [comment]
<img width="882" alt="屏幕截图 2023-06-02 185940" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/7ad03828-0065-4e1d-8067-8429e7425398">

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/4443e3c7-03f1-415e-b09a-8212dfc922b9)

**Comment by syr2212061031** [comment]
![J0XTWRT`EK~9JC4S(H03YKB](https://github.com/umdreamer/leetcodeproblems/assets/132579828/fca67a71-9b02-4684-b241-3a6ffa9708a5)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/fa2d36f9-ba01-4007-8077-dad463dc3677)

**Comment by daowuwu** [comment]
![V7O%EQ2(Y(ZBG8JH}MY{0ZD](https://github.com/umdreamer/leetcodeproblems/assets/132571490/d2391cb7-56f9-429c-a7ef-e132215437ff)

**Comment by liu-si-han** [comment]
<img width="808" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/38e5ca88-3532-4c3c-b5ec-e7d58e375b7c">

**Comment by foxbou** [comment]
<img width="897" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/d78f93d1-ef7d-41ce-84c4-55cfa41f495c">

**Comment by bedauern** [comment]
<img width="794" alt="Snipaste_2023-06-02_20-37-12" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/0e33beff-1414-40cb-b82f-e4585c997fa2">

**Comment by wangshiqi7** [comment]
<img width="794" alt="Snipaste_2023-06-02_20-37-12" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/34c64d98-a015-4ee4-b471-f2e9c84f14d8">

**Comment by 686xiaozhang** [comment]
![QQ截图20230602195110](https://github.com/umdreamer/leetcodeproblems/assets/132082348/6114db10-eaa1-41ee-8d00-b9c7f8a5ad9b)

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/281b0c05-087e-4e82-a9e8-076ff2409a6d)

**Comment by 123lrb** [comment]
![L`4VQV1_ 7DSIWM%}JQLKEH](https://github.com/umdreamer/leetcodeproblems/assets/132526491/39180c03-c192-4be0-b8a1-6b34631b0e18)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-06-02 213022](https://github.com/umdreamer/leetcodeproblems/assets/117709686/29481f20-ccfd-477c-8ae1-a9241ed902a0)

**Comment by huangyumei1** [comment]
![QQ图片20230602214623](https://github.com/umdreamer/leetcodeproblems/assets/122475924/af021875-3f66-4910-9da3-3a97c942a2f5)

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/3c419380-01c7-495a-bb3a-358d9e149b09)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/ab882f74-dabe-40a8-b3b1-ded3439034bc)

**Comment by naqianqpg** [comment]
![7V{D@$ZTLIT{M(WUJXTL@{X](https://github.com/umdreamer/leetcodeproblems/assets/132567187/68db4f39-5f8f-4d0b-bce1-09a0046948e7)

**Comment by htywan** [comment]
![2](https://github.com/umdreamer/leetcodeproblems/assets/132428178/3dadc2a2-0cf9-4daa-bd08-b3b318d2541f)

**Comment by htywan** [comment]
![2](https://github.com/umdreamer/leetcodeproblems/assets/132428178/9bde204d-f316-4008-81ef-12fe844ffa78)

**Comment by zangfushuo** [comment]
<img width="668" alt="截屏2023-06-02 22 29 18" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/093f8dd5-52d4-423e-ad74-a58831ae7e6b">

**Comment by zyhzxy99** [comment]
![1NB@)9_XKKIAJ(5SOLJ2%ND](https://github.com/umdreamer/leetcodeproblems/assets/132050929/3cff9553-d171-41eb-9c4b-0b933f3be7c4)

**Comment by shylieisme** [comment]
![$ 7 FWV{OIDU`O 8RL616$W](https://github.com/umdreamer/leetcodeproblems/assets/132582721/ff74b1da-1fcb-4ecf-b490-c5fb23ed4845)
