### ISSUE TITLE
2023.6.3 Problem: 190. Reverse Bits

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#30]
190. Reverse Bits

[Problem Link](https://leetcode.cn/problems/reverse-bits/)

Reverse bits of a given 32 bits unsigned integer.

Note:

Note that in some languages, such as Java, there is no unsigned integer type. In this case, both input and output will be given as a signed integer type. They should not affect your implementation, as the integer's internal binary representation is the same, whether it is signed or unsigned.
In Java, the compiler represents the signed integers using [2's complement notation](https://en.wikipedia.org/wiki/Two%27s_complement). Therefore, in Example 2 above, the input represents the signed integer -3 and the output represents the signed integer -1073741825.
 

Example 1:

```
Input: n = 00000010100101000001111010011100
Output:    964176192 (00111001011110000010100101000000)
Explanation: The input binary string 00000010100101000001111010011100 represents the unsigned integer 43261596, so return 964176192 which its binary representation is 00111001011110000010100101000000.
```
Example 2:

```
Input: n = 11111111111111111111111111111101
Output:   3221225471 (10111111111111111111111111111111)
Explanation: The input binary string 11111111111111111111111111111101 represents the unsigned integer 4294967293, so return 3221225471 which its binary representation is 10111111111111111111111111111111.
``` 

Constraints:

* The input must be a binary string of length 32

**Comment by naqianqpg** [comment]
![TU3IDJL~X76R3 QYMI{71 D](https://github.com/umdreamer/leetcodeproblems/assets/132567187/5cf8d8ad-865d-4884-94b4-031c4bdd7293)

**Comment by liu-si-han** [comment]
<img width="791" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/06305132-01b4-4704-9213-41e70e125935">

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/3b23af5c-b752-4430-81cf-7ce2f280d1d3)

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/6983e101-0923-4615-bab7-0279ff864f7b)

**Comment by huangyumei1** [comment]
![QQ图片20230604111434](https://github.com/umdreamer/leetcodeproblems/assets/122475924/39851bd5-e49e-47dd-8a1a-47bcf4ccd9c5)

**Comment by gusuning** [comment]
<img width="951" alt="屏幕截图 2023-06-04 120958" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/8ad2f067-91aa-47cf-8f04-ad5b23d01dec">

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/e36904a9-c631-428a-95cb-8ebd44dd64ca)

**Comment by 123lrb** [comment]
![3H8KH$MSZP 7E@36I@K)Z)V](https://github.com/umdreamer/leetcodeproblems/assets/132526491/898970a2-90cc-4431-9b0b-a1fea33684b8)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/bab9cf3a-49a8-4213-b541-d3df4f12dd51)

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/1ba188b3-5b47-4aaa-98bc-cdaf65676d66)

**Comment by tangyexi** [comment]
<img width="906" alt="屏幕截图 2023-06-04 125337" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/cde71a0a-49ec-4f9b-9482-5f4c8227d64b">

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/8738572d-4a14-4864-bdd0-4ddc89b14362)

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/6836d663-6040-42b9-a26c-0b75061160ef)

**Comment by foxbou** [comment]
<img width="929" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/2c0ec17d-ddbf-4196-980b-218548df2e5c">

**Comment by FXL1006** [comment]
<img width="853" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/7ca8d7d3-c463-4599-a985-de04156dd1c5">

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/17f5c452-266a-447c-acc6-86880131381f)

**Comment by daowuwu** [comment]
![2AY7QS RW% PIDI`M YG08K](https://github.com/umdreamer/leetcodeproblems/assets/132571490/e9069ab9-e4d4-4547-a7cd-89050950bfca)

**Comment by cuixiao02** [comment]
<img width="632" alt="截屏2023-06-04 15 24 28" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/1478503a-a100-4728-bb0e-d474f88401cd">

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/fe2c5c85-d92d-42fe-b46f-8529864ad019)

**Comment by 686xiaozhang** [comment]
![QQ截图20230604161143](https://github.com/umdreamer/leetcodeproblems/assets/132082348/ee4c7b1f-cbf4-4e8a-a197-477d5a337867)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-06-04 162427](https://github.com/umdreamer/leetcodeproblems/assets/117709686/4b0209ad-8b88-4b1e-8b41-a4573b8cc82a)

**Comment by bedauern** [comment]
<img width="783" alt="Snipaste_2023-06-04_16-24-46" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/1a371c39-b7c4-40a1-b77c-86795a6909c5">

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/0ce957bf-7b9d-4846-a2d7-0746abbe1216)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-06-04 16 27 21" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/88fd6e4d-5c82-4076-a2c9-1abe19b1a3c3">

**Comment by mafanjia** [comment]
![Uploading IMG_2969.png…]()

**Comment by mafanjia** [comment]
![Uploading IMG_2969.jpeg…]()

**Comment by 24zlx** [comment]
![联想截图_20230604163449](https://github.com/umdreamer/leetcodeproblems/assets/132560099/61e62799-5ff7-47c5-aaf0-683403121c86)

**Comment by syr2212061031** [comment]
![5)O7HT5LZ2Q9(JU92K(VJ@R](https://github.com/umdreamer/leetcodeproblems/assets/132579828/2067f733-9f7c-4c1d-88d5-878aca6f8fe8)

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/0bac666c-b4fb-4711-b239-3b07df8fd133)

**Comment by zyhzxy99** [comment]
![{PAV`TC( ~TE@MTUSQZJRW4](https://github.com/umdreamer/leetcodeproblems/assets/132050929/a33aae8d-a0ab-4ad5-9995-496bfccb60f8)

**Comment by 12baoxingyu-6** [comment]
<img width="758" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/588eae43-ea05-4e5b-989b-c5d55fe995d9">

**Comment by mafanjia** [comment]
![截屏1](https://github.com/umdreamer/leetcodeproblems/assets/132454776/680d6cd3-9cd6-4819-ba2a-cd50b5f18415)

**Comment by mafanjia** [comment]
![1](https://github.com/umdreamer/leetcodeproblems/assets/132454776/d6ff8938-2ade-4399-b990-741cf06c0664)

**Comment by htywan** [comment]
![3](https://github.com/umdreamer/leetcodeproblems/assets/132428178/010c38b1-8e21-4dd7-a7b6-553b79852dcc)

**Comment by zangfushuo** [comment]
<img width="568" alt="截屏2023-06-04 20 53 35" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/fe664cd7-b75c-40a2-9bfe-7eb7243999a3">
[57自评表22级大外2B04班.docx](https://github.com/umdreamer/leetcodeproblems/files/11645653/57.22.2B04.docx)

**Comment by shylieisme** [comment]
![$ZK6K%KXB_O($Q5{TB60KRE](https://github.com/umdreamer/leetcodeproblems/assets/132582721/d8fb61c2-e556-441c-a96b-3b0e3dea47a3)
