### ISSUE TITLE
2023.6.5 Problem: 193. Valid Phone Numbers

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#31]
193. Valid Phone Numbers
[Problem Link](https://leetcode.cn/problems/valid-phone-numbers/)

Given a text file file.txt that contains a list of phone numbers (one per line), write a one-liner bash script to print all valid phone numbers.

You may assume that a valid phone number must appear in one of the following two formats: (xxx) xxx-xxxx or xxx-xxx-xxxx. (x means a digit)

You may also assume each line in the text file must not contain leading or trailing white spaces.

Example:

Assume that `file.txt` has the following content:
```
987-123-4567
123 456 7890
(123) 456-7890
```
Your script should output the following valid phone numbers:
```
987-123-4567
(123) 456-7890
```

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/a7d045cc-f9f6-47ce-a1f6-4890a5a7e1bd)

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/9ee70398-6bf7-49cc-9dee-a65de29a13c8)

**Comment by zyhzxy99** [comment]
![4VLX@Q% 5DUH%86PH2 CQQF](https://github.com/umdreamer/leetcodeproblems/assets/132050929/f849cfd9-b6ad-458d-aa2f-5ef85fda9b61)

**Comment by tangyexi** [comment]
<img width="795" alt="屏幕截图 2023-06-05 155836" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/bc213069-878d-48eb-af2d-ac0549cef04a">

**Comment by liu-si-han** [comment]
<img width="812" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/a03eda10-357a-4f96-b7c9-ff40613095ff">

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/584c343b-e6ea-4c22-87ea-f04cd1bcfd9f)

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/cada7635-c216-4bea-859e-4b044cb22c9c)

**Comment by daowuwu** [comment]
![E5FD$NI~9QE@4)4ENI H_8D](https://github.com/umdreamer/leetcodeproblems/assets/132571490/826462e6-1203-4034-8522-1929e2bb4a24)

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/581db135-e7af-4b72-8f79-295437bb4cab)

**Comment by cuixiao02** [comment]
<img width="622" alt="截屏2023-06-05 16 03 13" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/d567d5ae-a115-4d58-aee9-4b3488c7bf44">

**Comment by mafanjia** [comment]
![2](https://github.com/umdreamer/leetcodeproblems/assets/132454776/a1d37d9f-de76-4cae-90c0-0557e47d726c)

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/b31e34f5-dbaa-46cd-9905-da09c2c5c7e2)

**Comment by foxbou** [comment]
<img width="877" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/76d9af64-5a6e-40ca-842a-32b36ac0ef78">

**Comment by bedauern** [comment]
<img width="773" alt="Snipaste_2023-06-05_17-16-07" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/c3cbda1f-d778-43cf-9343-21c6893d6cfd">

**Comment by huangyumei1** [comment]
![QQ图片20230605175624](https://github.com/umdreamer/leetcodeproblems/assets/122475924/73ce61b6-427d-429f-b231-32e58a316bff)

**Comment by syr2212061031** [comment]
![AY08R DN1999WT5Y UPEB](https://github.com/umdreamer/leetcodeproblems/assets/132579828/71ff8716-6a06-4d4d-9089-a40b4fcf30b8)

**Comment by 12baoxingyu-6** [comment]
<img width="822" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/3056eab9-d7c2-42dd-81b9-cfe7af8b85d8">

**Comment by 686xiaozhang** [comment]
![QQ截图20230605202758](https://github.com/umdreamer/leetcodeproblems/assets/132082348/e06fe990-2b4b-4433-b584-a49cbd80ba70)

**Comment by FXL1006** [comment]
<img width="813" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/228200f9-a7c7-4396-a4a7-20793d2588dd">

**Comment by Lggg1234** [comment]
![屏幕截图 2023-06-05 115542](https://github.com/umdreamer/leetcodeproblems/assets/117709686/856cbd6a-331f-4558-a7b0-b9dfbf1f213d)

**Comment by 24zlx** [comment]
![联想截图_20230605204240](https://github.com/umdreamer/leetcodeproblems/assets/132560099/3024f17b-5cb7-4dab-b750-69c95b5cd5d2)

**Comment by 123lrb** [comment]
![SW5_W_L346SQY `6R~HCE$4](https://github.com/umdreamer/leetcodeproblems/assets/132526491/84e06d34-153f-458b-8eb0-3e00ef40313c)

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/2c1f3073-90b2-4cf1-a425-51afaf83eec0)

**Comment by gusuning** [comment]
<img width="905" alt="屏幕截图 2023-06-05 205438" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/4a09429d-1ed4-4dff-9cba-4dc8ceeda8f3">

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/d3ef815a-06bb-4aaa-bc91-cf7f162608d1)

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/beaa9eb9-1c90-4bc0-83da-431dcabfdeb0)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/74fe3cff-653f-47d8-92d1-5edccb7c050f)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-06-05 21 27 13" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/1c65faaa-81c9-4252-9df3-df1a985c96a1">

**Comment by naqianqpg** [comment]
![7U(MN`$GQ9LU 7P4DC4~J5X](https://github.com/umdreamer/leetcodeproblems/assets/132567187/abcd4bc1-5cd5-4aa1-8e3b-17776e167af6)

**Comment by htywan** [comment]
![4](https://github.com/umdreamer/leetcodeproblems/assets/132428178/c9f4e3ea-dc31-4c4f-b833-38174290df5e)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/7bcedbfc-6176-444d-adb7-47ec707af3dc)

**Comment by shylieisme** [comment]
![O{BYQ M4RFAAFX{2YN)`E84](https://github.com/umdreamer/leetcodeproblems/assets/132582721/5c3cdcdf-f0fa-481e-b519-5358ac39ea81)
