### ISSUE TITLE
2023.6.6 Problem: 258. Add Digits

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#32]
258. Add Digits 
[Problem Link](https://leetcode.cn/problems/add-digits/)

Given an integer num, repeatedly add all its digits until the result has only one digit, and return it.

 

Example 1:
```
Input: num = 38
Output: 2
Explanation: The process is
38 --> 3 + 8 --> 11
11 --> 1 + 1 --> 2 
Since 2 has only one digit, return it.
```
Example 2:
```
Input: num = 0
Output: 0
``` 

Constraints:

* `0 <= num <= 231 - 1`

**Comment by 686xiaozhang** [comment]
![QQ截图20230606214731](https://github.com/umdreamer/leetcodeproblems/assets/132082348/7bbec7db-642e-4e82-9d6f-ec99a518a5f9)

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/a849962a-cc0c-406c-8f66-89688805c4e2)

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/7c206f50-75ac-497d-b280-da01f93409f6)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-06-05 115542](https://github.com/umdreamer/leetcodeproblems/assets/117709686/842ef353-874e-421d-a466-a44ac5d568b9)

**Comment by 24zlx** [comment]
![联想截图_20230607123828](https://github.com/umdreamer/leetcodeproblems/assets/132560099/dec1e0af-ae13-45c3-a536-2dea1ac22a2d)

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/1014e66d-3556-4961-858a-979622a95606)

**Comment by 123lrb** [comment]
![{@1C8U{L}5WW@M}HE6NEVEW](https://github.com/umdreamer/leetcodeproblems/assets/132526491/ed6b7f1a-4c56-46ac-a9cf-118d092a7497)

**Comment by tangyexi** [comment]
<img width="826" alt="屏幕截图 2023-06-07 152242" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/902b4fc2-b0fe-43a8-b4e2-3903b9e99094">

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/a013a1bd-fa15-477a-a4f5-8c9d9f55885b)

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/d05f1cb7-d6d3-4b5e-a5c7-594e74d65c10)

**Comment by syr2212061031** [comment]
![FM1 YXV14{}DWN9CDF7(FGA](https://github.com/umdreamer/leetcodeproblems/assets/132579828/6eb26803-1f12-4f80-ac76-4ea0fc1ace63)

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/05041843-e893-452d-9ed3-7cba9393422e)

**Comment by mafanjia** [comment]
![258](https://github.com/umdreamer/leetcodeproblems/assets/132454776/184939f0-cbe7-427c-bee7-1f4e8fc9071e)

**Comment by daowuwu** [comment]
![)S~PYO_K3AZ2P2Z54BJGBRG](https://github.com/umdreamer/leetcodeproblems/assets/132571490/749c82dc-0b7d-448f-a1a3-4ba1856a4c5a)

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/aa876ebc-240d-43c9-81fe-167beb6159cf)

**Comment by cuixiao02** [comment]
<img width="620" alt="截屏2023-06-07 16 44 27" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/23c6ff09-ebd3-4460-a636-71595591a15a">

**Comment by bedauern** [comment]
<img width="820" alt="Snipaste_2023-06-07_16-53-54" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/1f76801c-c258-4832-8f9f-02a2ec183306">

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-06-07 17 16 44" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/899f5c59-4218-4100-a08e-c2bdb0b2339c">

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/9da5bec1-e6cc-4c48-bee0-3d36248f5523)

**Comment by gusuning** [comment]
<img width="896" alt="屏幕截图 2023-06-07 172655" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/44630967-88d2-445e-b458-8b745c7089e0">

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/d13ebf01-f1e2-4ae2-9453-ad9a2478e07b)

**Comment by liu-si-han** [comment]
<img width="786" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/bf4d8206-fcaa-4fcb-9089-d2071a295fc3">

**Comment by 12baoxingyu-6** [comment]
<img width="845" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/0d58a62b-c06c-4f8a-a853-5a1da62815ee">

**Comment by xkqwww** [comment]
![1](https://github.com/umdreamer/leetcodeproblems/assets/132559761/d7440f1c-ad64-4b46-b25b-cf0e758f175e)

**Comment by zyhzxy99** [comment]
![$_UE66)C UXJXR67N$LXR3F](https://github.com/umdreamer/leetcodeproblems/assets/132050929/cadef326-9617-4b2b-a032-afb7de034df3)

**Comment by FXL1006** [comment]
<img width="729" alt="屏幕截图 2023-06-07 213621" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/72b45cd7-6fc8-4abd-a580-da9591c9f053">

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/4d92391b-ab85-4761-aeb9-233524c3b592)

**Comment by foxbou** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526020/1621dafd-fcbd-4ea5-bdd4-581c51aaedea)
