### ISSUE TITLE
2023.6.7 Problem: 290. Word Pattern

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#33]
290. Word Pattern
[Problem Link](https://leetcode.cn/problems/word-pattern/)
Given a pattern and a string s, find if s follows the same pattern.

Here follow means a full match, such that there is a bijection between a letter in pattern and a non-empty word in s.

Example 1:
```
Input: pattern = "abba", s = "dog cat cat dog"
Output: true
```
Example 2:
```
Input: pattern = "abba", s = "dog cat cat fish"
Output: false
```
Example 3:
```
Input: pattern = "aaaa", s = "dog cat cat dog"
Output: false
``` 

Constraints:

* 1 <= pattern.length <= 300
* pattern contains only lower-case English letters.
* 1 <= s.length <= 3000
* s contains only lowercase English letters and spaces ' '.
* s does not contain any leading or trailing spaces.
* All the words in s are separated by a single space.

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/c46168d0-a3e8-4a4b-b41c-3261dbf90e20)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-06-05 115542](https://github.com/umdreamer/leetcodeproblems/assets/117709686/f29a2680-d3f3-4236-9341-b992c3b7fcdb)

**Comment by 24zlx** [comment]
![联想截图_20230607124038](https://github.com/umdreamer/leetcodeproblems/assets/132560099/6c49c589-8912-4e1b-828a-908f685947b2)

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/3f1cd130-faa8-448a-8242-26bd0a3833ca)

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/d8e816f3-177e-4be6-8b4c-390d479d3bb8)

**Comment by 123lrb** [comment]
![M0PT1N_H0YX0K%W$AYULKZS](https://github.com/umdreamer/leetcodeproblems/assets/132526491/b6e47152-5236-408f-8535-e9c951cd12e2)

**Comment by huangyumei1** [comment]
![QQ图片20230607151840](https://github.com/umdreamer/leetcodeproblems/assets/122475924/f1847045-1f1f-4c94-88ff-f040ab3dcca7)

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/6e88b740-9005-4219-85f1-a6c85417cd78)

**Comment by tangyexi** [comment]
<img width="796" alt="屏幕截图 2023-06-07 152444" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/d24f9943-e83a-4079-bbf9-9ac66e4f9b27">

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/274dbb85-cf36-42c7-bbb9-ca7cef1465b0)

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/ba2c5544-aef2-44a1-95da-96c5755a6734)

**Comment by syr2212061031** [comment]
![})D~QGSPC)U0P8 21OK6 CI](https://github.com/umdreamer/leetcodeproblems/assets/132579828/c1dc572b-48a2-418a-acc4-c96b206054b8)

**Comment by shylieisme** [comment]
![1TTNIVK4L E92{$OH117S@Q](https://github.com/umdreamer/leetcodeproblems/assets/132582721/b4fd1876-1956-436e-b822-52c17e601756)

**Comment by mafanjia** [comment]
![290](https://github.com/umdreamer/leetcodeproblems/assets/132454776/9b606869-f5fc-48de-9182-4b6cb8e5dc78)

**Comment by daowuwu** [comment]
![3(KM5G614K_2PWI$ B~%}RQ](https://github.com/umdreamer/leetcodeproblems/assets/132571490/f7027fab-4a5f-4f24-a265-1b38a2d391d1)

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/2e63da8b-9fe9-44b1-a02f-effbbed80d16)

**Comment by cuixiao02** [comment]
<img width="641" alt="截屏2023-06-07 16 46 10" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/8b6c5e4a-a54a-4a37-9273-c907f6e19c0a">

**Comment by bedauern** [comment]
<img width="803" alt="Snipaste_2023-06-07_16-54-58" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/ce5daf51-4350-4cfb-9333-24410e211075">

**Comment by naqianqpg** [comment]
![DCQ@QPAX4KX7D%F)_ CL0WG](https://github.com/umdreamer/leetcodeproblems/assets/132567187/927e7e9a-517c-4c82-a735-50a8ff9f4649)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-06-07 17 18 28" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/cea96470-a093-4276-80b8-acc9b14be29c">

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/cd239ee8-481c-4dcf-80ca-831951ffacfa)

**Comment by gusuning** [comment]
<img width="896" alt="屏幕截图 2023-06-07 172655" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/fbc942cd-d9c4-42f6-b970-ace75341d870">

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/d467e910-0200-4176-84bd-0864342b911c)

**Comment by liu-si-han** [comment]
<img width="815" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/3f6503cf-88e5-40d4-b522-f07ce3fe01f8">

**Comment by 12baoxingyu-6** [comment]
<img width="827" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/c47baa97-3417-4104-9190-3dfcce1c0e8a">

**Comment by 686xiaozhang** [comment]
![QQ截图20230607184837](https://github.com/umdreamer/leetcodeproblems/assets/132082348/220ae2be-5e18-462e-bf0a-869e8eaf1571)

**Comment by xkqwww** [comment]
![2](https://github.com/umdreamer/leetcodeproblems/assets/132559761/c3a21dc3-548d-4a67-a4ef-3b7d335da408)

**Comment by zyhzxy99** [comment]
![P1I %52Y985U(~%S{{2Q$2](https://github.com/umdreamer/leetcodeproblems/assets/132050929/299d3b2a-382f-4278-9fb7-b56ea65a4d84)

**Comment by FXL1006** [comment]
<img width="806" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/ba368450-8030-4a77-a248-6920f470a69a">

**Comment by zangfushuo** [comment]
<img width="695" alt="截屏2023-05-24 22 39 27" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/8542ba96-01ba-4abf-9876-a3bdc3647ca4">

**Comment by htywan** [comment]
![5](https://github.com/umdreamer/leetcodeproblems/assets/132428178/b814e182-7d72-47e1-8f55-09797b1a736f)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/2dc4f4b4-8388-4334-98ab-e63cc44e098e)

**Comment by foxbou** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526020/8c5b744d-9da7-426c-9b92-0cbf301d251a)
