### ISSUE TITLE
2023.5.5 Problem: 9. Palindrome Number

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#5]
9. Palindrome Number
[Problem Link](https://leetcode.cn/problems/palindrome-number/)

Given an integer x, return true if x is a palindrome, and false otherwise.

Example 1:

```
Input: x = 121
Output: true
Explanation: 121 reads as 121 from left to right and from right to left.
```

Example 2:
```
Input: x = -121
Output: false
Explanation: From left to right, it reads -121. From right to left, it becomes 121-. Therefore it is not a palindrome.
```

Example 3:
```
Input: x = 10
Output: false
Explanation: Reads 01 from right to left. Therefore it is not a palindrome.
```

**Comment by yeyuxq** [comment]
![image](https://user-images.githubusercontent.com/128273789/236354516-bdf1e018-2dba-47b2-b328-77338cb5d391.png)

**Comment by ZWJ2212061008** [comment]
![image](https://user-images.githubusercontent.com/132138380/236408410-5619ffce-4ea9-4913-9f3e-8a1cd8d2673e.png)

**Comment by huangyumei1** [comment]
![QQ图片20230505163158](https://user-images.githubusercontent.com/122475924/236411864-7f32c1ce-3a80-4dab-b827-532501cc62c6.png)

**Comment by bedauern** [comment]
<img width="897" alt="Snipaste_2023-05-05_16-32-11" src="https://user-images.githubusercontent.com/132483498/236411948-4302cefa-81ea-4e90-8cce-4cc6c06485f6.png">

**Comment by shylieisme** [comment]
![FZ~6E9B7N$1`0498~0P70R0](https://user-images.githubusercontent.com/132582721/236412540-efc7a42f-4c4f-4ab1-922d-cf7f2d1c82e8.png)

**Comment by mafanjia** [comment]
![截屏2](https://user-images.githubusercontent.com/132454776/236412829-016cc561-c6cd-43a4-92d5-3dd676f41e41.png)

**Comment by sjh397** [comment]
![联想截图_20230505164143](https://user-images.githubusercontent.com/132568283/236413862-bf4d2bbc-1bfc-4a9c-8bcb-9f4a39a61493.png)

**Comment by PinkyLame** [comment]
![1](https://user-images.githubusercontent.com/132571584/236414320-2e575ef8-776f-4546-8e9b-7235a1528807.png)

**Comment by PinkyLame** [comment]
![12](https://user-images.githubusercontent.com/132571584/236414651-a50ec76e-eb9f-4365-aeb8-bd9dff415e5c.png)

**Comment by liu-si-han** [comment]
![Uploading image.png…]()

**Comment by liu-si-han** [comment]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/132453391/236416286-b352704f-31f6-4d98-9f33-46f27afec3f6.png">

**Comment by zhjingyan** [comment]
![image](https://user-images.githubusercontent.com/132195009/236416653-954d0196-bf21-4da0-bbe5-116b634ab5cd.png)

**Comment by 12baoxingyu-6** [comment]
![image](https://user-images.githubusercontent.com/132574617/236417818-4f8aac7b-1d53-4f52-a459-a246baa7e6e2.png)

**Comment by tangyexi** [comment]
<img width="847" alt="屏幕截图 2023-05-05 165947" src="https://user-images.githubusercontent.com/132453549/236417981-a9f4e852-0cbf-47a4-accb-fc7c5c303e1f.png">

**Comment by 123lrb** [comment]
![IDT(Q(S~6}$JZXV)KKPQ~66](https://user-images.githubusercontent.com/132526491/236418078-2f3daf33-5cbc-4251-a531-0c9ee7636d04.png)

**Comment by xkqwww** [comment]
![无标题](https://user-images.githubusercontent.com/132559761/236418701-1a6b6cc1-c059-455a-813a-1a37ec437114.png)

**Comment by daowuwu** [comment]
![V08NAZ{BSU_9UG6Q2T}KF2U](https://user-images.githubusercontent.com/132571490/236419557-da36092e-26e1-462e-a927-f6f47c64e961.png)

**Comment by htywan** [comment]
![2](https://user-images.githubusercontent.com/132428178/236420565-924e650b-dfd7-4451-8a2f-3d3776f69803.png)

**Comment by 686xiaozhang** [comment]
![QQ截图20230505180822](https://user-images.githubusercontent.com/132082348/236431004-24a5efae-f291-49f6-b926-7223217ec8ce.png)

**Comment by promisewith7** [comment]
![image](https://user-images.githubusercontent.com/132559311/236435346-68735347-efe8-4419-9a97-6ad91e3d39f7.png)

**Comment by 1125766961** [comment]
![image](https://user-images.githubusercontent.com/132560784/236439813-a3e69f3a-be2a-410f-9937-8b5a44b0947b.png)

**Comment by zxm-1235** [comment]
![image](https://user-images.githubusercontent.com/132538992/236440532-42f2822e-ae2c-419e-99b1-ef959b20e739.png)

**Comment by gusuning** [comment]
<img width="921" alt="屏幕截图 2023-05-05 190349" src="https://user-images.githubusercontent.com/126148849/236441733-c31ae920-9aa7-4393-a664-f66e4278b6de.png">

**Comment by qby962464** [comment]
![Snipaste_2023-05-05_19-15-41](https://user-images.githubusercontent.com/132563315/236444169-fa81abec-1a7b-4633-9dc9-1012c67960a3.png)

**Comment by FXL1006** [comment]
<img width="960" alt="屏幕截图 2023-05-05 191812" src="https://user-images.githubusercontent.com/132453630/236445007-e8a092c4-cd34-4955-801e-fd2a6a596eaa.png">

**Comment by liuhuanyu6** [comment]
![image](https://user-images.githubusercontent.com/132526191/236445972-b293aeac-d57f-4e7b-928f-74330c464c42.png)

**Comment by xiaolu2002** [comment]
![image](https://user-images.githubusercontent.com/132567090/236446025-bec0976c-a4ce-46f1-80ee-0db3de9a36a5.png)

**Comment by cuixiao02** [comment]
<img width="1280" alt="截屏2023-05-05 19 33 36" src="https://user-images.githubusercontent.com/132454083/236447497-725cf5ab-6ac2-40a9-a9a0-73de673ff37a.png">

**Comment by foxbou** [comment]
![DG{WOR~PX(1U(KW 9K$5N7E](https://user-images.githubusercontent.com/132526020/236448496-47361619-24bd-48f4-a914-1c1e1bc275a7.png)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-05 194450](https://user-images.githubusercontent.com/117709686/236450453-d94c9440-9416-4959-87b2-2d27a5bcbf93.png)

**Comment by naqianqpg** [comment]
![~Q3I$7RM G_O5T_310_3GSE](https://user-images.githubusercontent.com/132567187/236454927-045a0519-5643-4055-a92f-8de64fe69db4.png)

**Comment by 24zlx** [comment]
![联想截图_20230505202405](https://user-images.githubusercontent.com/132560099/236457533-44c8c2ac-d46e-4f9e-90b6-55ac926a4235.png)

**Comment by zangfushuo** [comment]
<img width="682" alt="截屏2023-05-04 19 44 22的副本" src="https://user-images.githubusercontent.com/132563136/236472922-03af003f-2947-404e-92f6-049b9f1a6cef.png">

**Comment by zyhzxy99** [comment]
![DP)RZF8_T2` 5FE57~VVZ6K](https://user-images.githubusercontent.com/132050929/236508113-bc08cd4a-b1f1-476f-868c-07dec8d8a725.png)

**Comment by syr2212061031** [comment]
![3_~EDJ%J)J3RSVD2@4A{4OR](https://user-images.githubusercontent.com/132579828/236652442-76ffc3dd-a317-4b95-a51e-395abce657c1.png)

**Comment by naqianqpg** [comment]
![~Q3I$7RM G_O5T_310_3GSE](https://user-images.githubusercontent.com/132567187/236672799-6fdbd1cc-1b37-40bf-85fc-a8a613a3ddb1.png)
