### ISSUE TITLE
2023.5.6 Problem: 13. Roman to Integer

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#6]
13. Roman to Integer
[Problem Link](https://leetcode.cn/problems/roman-to-integer/)

Roman numerals are represented by seven different symbols: I, V, X, L, C, D and M.
```
Symbol       Value
I             1
V             5
X             10
L             50
C             100
D             500
M             1000
```
For example, 2 is written as II in Roman numeral, just two ones added together. 12 is written as XII, which is simply X + II. The number 27 is written as XXVII, which is XX + V + II.

Roman numerals are usually written largest to smallest from left to right. However, the numeral for four is not IIII. Instead, the number four is written as IV. Because the one is before the five we subtract it making four. The same principle applies to the number nine, which is written as IX. There are six instances where subtraction is used:

* I can be placed before V (5) and X (10) to make 4 and 9. 
* X can be placed before L (50) and C (100) to make 40 and 90. 
* C can be placed before D (500) and M (1000) to make 400 and 900.
Given a roman numeral, convert it to an integer.

Example 1:
```
Input: s = "III"
Output: 3
Explanation: III = 3.
```
Example 2:
```
Input: s = "LVIII"
Output: 58
Explanation: L = 50, V= 5, III = 3.
```
Example 3:
```
Input: s = "MCMXCIV"
Output: 1994
Explanation: M = 1000, CM = 900, XC = 90 and IV = 4.
``` 

Constraints:
* 1 <= s.length <= 15
* s contains only the characters ('I', 'V', 'X', 'L', 'C', 'D', 'M').
* It is guaranteed that s is a valid roman numeral in the range [1, 3999].

**Comment by zxm-1235** [comment]
![image](https://user-images.githubusercontent.com/132538992/236615048-d05eef7b-3937-4214-8094-827f02c8fe50.png)

**Comment by bedauern** [comment]
<img width="906" alt="Snipaste_2023-05-06_17-09-18" src="https://user-images.githubusercontent.com/132483498/236615574-d81892e5-ee11-4935-8446-6afb064ebe31.png">

**Comment by mafanjia** [comment]
![截屏3](https://user-images.githubusercontent.com/132454776/236616291-5bb58244-c646-4f16-8b48-88ec4dc141c8.png)

**Comment by ZWJ2212061008** [comment]
![image](https://user-images.githubusercontent.com/132138380/236616309-75a9245a-5021-4dcb-9ac0-5627a1c06d79.png)

**Comment by foxbou** [comment]
![Z97N @UDCLP$)IUL U7U{}N](https://user-images.githubusercontent.com/132526020/236618991-2ad4a06c-3dc8-4692-94c8-da98581efc7b.png)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-06 185451](https://user-images.githubusercontent.com/117709686/236620038-dce4764e-7f6f-48e7-a885-b7bcbeca5de3.png)

**Comment by xkqwww** [comment]
![无标题1](https://user-images.githubusercontent.com/132559761/236620096-727295fd-a7d9-4d89-9e29-af336e7b6448.png)

**Comment by liuhuanyu6** [comment]
![image](https://user-images.githubusercontent.com/132526191/236620218-9b0e0d8b-3d03-4985-bece-d238aa8536d8.png)

**Comment by 123lrb** [comment]
![F6I)P~KAYJG8VIPT@K4)893](https://user-images.githubusercontent.com/132526491/236620384-dcd0d5d9-fc81-4d86-83a7-fd8775820be7.png)

**Comment by liu-si-han** [comment]
<img width="764" alt="image" src="https://user-images.githubusercontent.com/132453391/236620425-5c5335b2-2037-48dd-abfe-59cb9fc8f81d.png">

**Comment by htywan** [comment]
![3](https://user-images.githubusercontent.com/132428178/236620517-6bbd02a0-69ac-4087-8673-23288dab89d4.png)

**Comment by PinkyLame** [comment]
![3](https://user-images.githubusercontent.com/132571584/236620591-921a5368-b7ee-4b59-b02a-9f8384f91aef.png)

**Comment by 686xiaozhang** [comment]
![QQ截图20230506190913](https://user-images.githubusercontent.com/132082348/236620614-e1bfd7fe-795a-4cc2-97d1-557e67762b4a.png)

**Comment by tangyexi** [comment]
<img width="861" alt="屏幕截图 2023-05-06 191421" src="https://user-images.githubusercontent.com/132453549/236620813-6b3d1683-90e0-44eb-8136-e81b9423d9a3.png">

**Comment by sjh397** [comment]
![image](https://user-images.githubusercontent.com/132568283/236620858-0a0f1d76-9bd9-4cf5-9737-ee3c109e04e9.png)

**Comment by zyhzxy99** [comment]
![FRVQZ)HM4X%HVNW{W R 3](https://user-images.githubusercontent.com/132050929/236620948-3de5101f-a0ea-4052-aa89-6dcae616bf72.png)

**Comment by huangyumei1** [comment]
![QQ图片20230506194054](https://user-images.githubusercontent.com/122475924/236621898-6040d8f4-edc0-47e9-8d1b-77369fd4c3cf.png)

**Comment by zhjingyan** [comment]
![image](https://user-images.githubusercontent.com/132195009/236622082-dfd30905-ac0a-4c3b-86c8-78548bad800b.png)

**Comment by cuixiao02** [comment]
<img width="1280" alt="截屏2023-05-06 19 51 25" src="https://user-images.githubusercontent.com/132454083/236622322-39df4bd6-c9a5-4e1c-b662-bc96c934c225.png">

**Comment by naqianqpg** [comment]
![@N2WK}OCT(@6X$H WU5UPEM](https://user-images.githubusercontent.com/132567187/236622597-ace64728-7d76-472e-827b-466fbb39472e.png)

**Comment by daowuwu** [comment]
![V08NAZ{BSU_9UG6Q2T}KF2U](https://user-images.githubusercontent.com/132571490/236622806-b47078c5-ccf1-426c-b5bd-5e26bba5e329.png)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-06 20 01 23" src="https://user-images.githubusercontent.com/132578339/236623030-492ccf58-feff-46b2-ae7f-88b572ff6baa.png">

**Comment by 12baoxingyu-6** [comment]
![image](https://user-images.githubusercontent.com/132574617/236623182-81ffb971-6def-4b6c-87c1-3ed07ceef015.png)

**Comment by xiaolu2002** [comment]
![image](https://user-images.githubusercontent.com/132567090/236624978-0ba46d16-7e32-4dea-a2fc-1d45e2308bd9.png)

**Comment by promisewith7** [comment]
![image](https://user-images.githubusercontent.com/132559311/236625742-332c2b8d-87e3-43f2-b06a-f5af93437e19.png)

**Comment by qby962464** [comment]
![image](https://user-images.githubusercontent.com/132563315/236625788-699bf1c2-6ef7-42d8-94f2-70bba5b3f909.png)

**Comment by 1125766961** [comment]
![image](https://user-images.githubusercontent.com/132560784/236626428-3254050d-b482-4dd4-a6bd-dbb57331cd98.png)

**Comment by syr2212061031** [comment]
![K$DWN{YDD4 MS67`)3MDAGY](https://user-images.githubusercontent.com/132579828/236626854-b70e8ee5-a4b9-45c8-855e-e4295063e63e.png)

**Comment by FXL1006** [comment]
![image](https://user-images.githubusercontent.com/132453630/236627872-57dde055-1d93-41e2-b109-2b689f324625.png)

**Comment by gusuning** [comment]
<img width="882" alt="屏幕截图 2023-05-06 214246" src="https://user-images.githubusercontent.com/126148849/236627917-efac9b2e-9c48-4f6c-9af0-f1d7a04484e6.png">

**Comment by zangfushuo** [comment]
<img width="708" alt="截屏2023-05-06 21 57 04" src="https://user-images.githubusercontent.com/132563136/236629065-468878c7-a937-44db-bfe0-954947a0a7d9.png">

**Comment by 24zlx** [comment]
![联想截图_20230506220901](https://user-images.githubusercontent.com/132560099/236629187-efbf4543-235a-40fa-b4ec-5c8824823e22.png)

**Comment by yeyuxq** [comment]
![image](https://user-images.githubusercontent.com/128273789/236631257-94476aef-0bba-49fa-8bb2-bdf2f9b5bc4b.png)

**Comment by shylieisme** [comment]
![{V8)P003EP2CE{7)SM5QZVG](https://user-images.githubusercontent.com/132582721/236631344-f65f1b97-87dc-428a-8440-94b80ebbe256.png)
