### ISSUE TITLE
2023.5.8 Problem: 14. Longest Common Prefix

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#7]
14. Longest Common Prefix
[Problem Link](https://leetcode.cn/problems/longest-common-prefix/)

Write a function to find the longest common prefix string amongst an array of strings.

If there is no common prefix, return an empty string "".

Example 1:
```
Input: strs = ["flower","flow","flight"]
Output: "fl"
```
Example 2:
```
Input: strs = ["dog","racecar","car"]
Output: ""
Explanation: There is no common prefix among the input strings.
``` 

Constraints:

* 1 <= strs.length <= 200
* 0 <= strs[i].length <= 200
* strs[i] consists of only lowercase English letters.

**Comment by yeyuxq** [comment]
![image](https://user-images.githubusercontent.com/128273789/236709029-27cebd91-6dfa-488d-ab98-afe0d3e82823.png)

**Comment by tangyexi** [comment]
<img width="848" alt="屏幕截图 2023-05-08 191754" src="https://user-images.githubusercontent.com/132453549/236810703-21c4cb6b-e349-4e81-952b-852263f4b428.png">

**Comment by zhjingyan** [comment]
![image](https://user-images.githubusercontent.com/132195009/236811431-d1b1e2fd-8a51-4991-88ba-0b93845d3912.png)

**Comment by sjh397** [comment]
![image](https://user-images.githubusercontent.com/132568283/236811497-a158fc91-ab03-4f26-88b0-c08c237d514e.png)

**Comment by cuixiao02** [comment]
<img width="1280" alt="截屏2023-05-08 19 26 27" src="https://user-images.githubusercontent.com/132454083/236812953-6ae7d39b-081a-416a-92a6-833dce407690.png">

**Comment by liu-si-han** [comment]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/132453391/236813781-a7fdf433-ba4f-4f5d-9b51-d6b8793fab3b.png">

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-08 18 50 33" src="https://user-images.githubusercontent.com/132578339/236814044-2c749125-7a98-4c25-a039-7bea9a0603c1.png">

**Comment by 12baoxingyu-6** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/132574617/236819131-97350326-ac6f-47e5-bb88-68aa30f217e2.png">

**Comment by daowuwu** [comment]
![V6IRR1~T){(B2Y%TUTA(G5B](https://user-images.githubusercontent.com/132571490/236820820-980a92e1-1b63-4054-8a6a-688c12dddce2.png)

**Comment by PinkyLame** [comment]
![联想截图_20230508201251](https://user-images.githubusercontent.com/132571584/236822767-1157d02b-50fb-42e4-91f9-1dc2303e9344.png)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-08 115512](https://user-images.githubusercontent.com/117709686/236824281-e7343196-0187-489d-8d9c-7fc6fa872f6e.png)

**Comment by zxm-1235** [comment]
![image](https://user-images.githubusercontent.com/132538992/236828305-03fd8705-803c-4a32-ab82-20cf37bb4a8e.png)

**Comment by 123lrb** [comment]
![)@G 8E3IS9ODAX{W5OS2KX](https://user-images.githubusercontent.com/132526491/236829309-b7c761eb-dfe1-460e-9a82-f249db234a64.png)

**Comment by liuhuanyu6** [comment]
![image](https://user-images.githubusercontent.com/132526191/236829344-04c5817b-adb1-47b8-96fb-9eb1a4a0df81.png)

**Comment by mafanjia** [comment]
![截屏4](https://user-images.githubusercontent.com/132454776/236830041-a8dd124c-dfa0-4dc6-95bc-18c3e7cbcbc4.png)

**Comment by huangyumei1** [comment]
![QQ图片20230508205634](https://user-images.githubusercontent.com/122475924/236830137-abf83c07-95cc-47a5-bf26-a46e6bb83e38.png)

**Comment by syr2212061031** [comment]
![`G%{_QR66WXCE1J@~3SV$NU](https://user-images.githubusercontent.com/132579828/236830346-1ca43e17-cd55-4052-ba5b-f97e67f2ac0a.png)

**Comment by naqianqpg** [comment]
![W123D4DKJ PYCRHPFXZ@Q9K](https://user-images.githubusercontent.com/132567187/236830373-73fb986e-7c9e-4f1d-8d04-d292e7ee2f4e.png)

**Comment by htywan** [comment]
![4](https://user-images.githubusercontent.com/132428178/236831702-fc6340af-d8a1-4a96-b49b-827c757df149.png)

**Comment by ZWJ2212061008** [comment]
![image](https://user-images.githubusercontent.com/132138380/236833074-c445084a-16cd-405c-a262-f52d876005e2.png)

**Comment by foxbou** [comment]
![0I%`22Y6)3KBBC3YIPS6@B](https://user-images.githubusercontent.com/132526020/236834165-2b2970b4-f1f5-4d9d-a609-43f2ce30bdcb.png)

**Comment by FXL1006** [comment]
<img width="857" alt="屏幕截图 2023-05-08 202732" src="https://user-images.githubusercontent.com/132453630/236834684-eea724b4-76c0-4427-afb8-57e76995bfff.png">

**Comment by 1125766961** [comment]
![image](https://user-images.githubusercontent.com/132560784/236835302-74de1fe5-ec1e-48d9-954a-53ec20154d06.png)

**Comment by promisewith7** [comment]
![image](https://user-images.githubusercontent.com/132559311/236832860-f2ef58ab-0884-4a79-be17-fed856418898.png)

**Comment by bedauern** [comment]
<img width="855" alt="Snipaste_2023-05-08_21-14-13" src="https://user-images.githubusercontent.com/132483498/236836159-89a1dd8c-8041-4c88-a073-e56ac9f772b2.png">

**Comment by 686xiaozhang** [comment]
![QQ截图20230508213514](https://user-images.githubusercontent.com/132082348/236838312-0bca54ae-6890-44ee-8dbb-29e96c103b50.png)

**Comment by 24zlx** [comment]
![联想截图_20230508215036](https://user-images.githubusercontent.com/132560099/236841832-5c22e28c-fa90-4d25-a1eb-1a4b4cc4bc4e.png)

**Comment by xkqwww** [comment]
![3](https://user-images.githubusercontent.com/132559761/236842238-80c1c9ff-3735-4924-aeb2-5caa7d300a53.png)

**Comment by xiaolu2002** [comment]
![image](https://user-images.githubusercontent.com/132567090/236853466-1f869c06-84b9-4392-9534-cf25400d0e10.png)

**Comment by zyhzxy99** [comment]
![HQ0_(RUQJS2R2EFNJ}T40ZE](https://user-images.githubusercontent.com/132050929/236858052-318b1654-cc2f-4091-9676-fa14d2158cce.png)

**Comment by shylieisme** [comment]
![S{RN_$@(T6WCJ1WLF 0VP}1](https://user-images.githubusercontent.com/132582721/236858447-4c1e3946-6ada-418d-ab54-f0d237ca5ae4.png)

**Comment by zangfushuo** [comment]
<img width="674" alt="截屏2023-05-08 22 58 09" src="https://user-images.githubusercontent.com/132563136/236858608-60116967-1bba-461f-9d25-32e38bfaa5d7.png">

**Comment by gusuning** [comment]
<img width="893" alt="屏幕截图 2023-05-09 074526" src="https://user-images.githubusercontent.com/126148849/236960322-e2f5fa51-f11d-498a-a73b-516d3413b1dd.png">

**Comment by 123lrb** [comment]
![@6% 2HU6L4SU}_@$4A7TPKU](https://github.com/umdreamer/leetcodeproblems/assets/132526491/8c1516f0-8481-4f04-afab-34c453223411)
