### ISSUE TITLE
2023.5.9 Problem: 20. Valid Parentheses

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#8]
20. Valid Parentheses 
[Problem Link](https://leetcode.cn/problems/valid-parentheses/)

Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.

An input string is valid if:

Open brackets must be closed by the same type of brackets.
Open brackets must be closed in the correct order.
Every close bracket has a corresponding open bracket of the same type.
 

Example 1:
```
Input: s = "()"
Output: true
```
Example 2:
```
Input: s = "()[]{}"
Output: true
```
Example 3:
```
Input: s = "(]"
Output: false
 ```

Constraints:

* 1 <= s.length <= 104
* s consists of parentheses only '()[]{}'.

**Comment by yeyuxq** [comment]
![image](https://user-images.githubusercontent.com/128273789/236996306-a33723b6-0e15-4814-9a27-97bef19cd980.png)

**Comment by naqianqpg** [comment]
![_ ELJJQ@$QX3}Z%(_9UG(HC](https://user-images.githubusercontent.com/132567187/237053110-395714c3-2b61-472d-8d72-433d36bac3de.png)

**Comment by promisewith7** [comment]
![image](https://user-images.githubusercontent.com/132559311/237058195-6912e982-805e-41fe-bb07-48837991643d.png)

**Comment by foxbou** [comment]
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/132526020/237062068-dadb0256-f57c-46f7-8fe8-74efc32dc528.png">

**Comment by zangfushuo** [comment]
![截屏2023-05-09 18 41 38](https://github.com/umdreamer/leetcodeproblems/assets/132563136/05b627bb-818f-412a-b898-7a1e29681082)

**Comment by daowuwu** [comment]
![%P8DI)}0(SDK%SAT90AJKA3](https://github.com/umdreamer/leetcodeproblems/assets/132571490/f926dc08-c47b-45fa-ba66-f2f17ed36361)

**Comment by liu-si-han** [comment]
<img width="830" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/0cf7a6cb-6938-45c7-8bf3-b86183db004b">

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-09 18 53 44" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/5ad13817-4356-4a54-bd04-98c4bf2c30e8">

**Comment by PinkyLame** [comment]
![联想截图_20230509190330](https://github.com/umdreamer/leetcodeproblems/assets/132571584/2bcbc325-fb1b-4270-bfc8-7aeb968d3fab)

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/49c34aec-c76d-46a5-af5b-38984ef88e78)

**Comment by mafanjia** [comment]
![截屏5](https://github.com/umdreamer/leetcodeproblems/assets/132454776/fea88346-6cc9-464d-ac00-05489f2de693)

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/73ab3bdd-2dba-478b-8e12-180840763d4f)

**Comment by tangyexi** [comment]
https://github.com/umdreamer/leetcodeproblems/issues/1

**Comment by tangyexi** [comment]
<img width="823" alt="屏幕截图 2023-05-09 190050" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/d09618d1-3342-4575-a497-c6ea969a4f34">

**Comment by zyhzxy99** [comment]
![CL__YUQ19VV@{9TV2)_U691](https://github.com/umdreamer/leetcodeproblems/assets/132050929/89c4689f-0f54-45ea-ba6c-1827b3c058b2)

**Comment by xkqwww** [comment]
![无标题](https://github.com/umdreamer/leetcodeproblems/assets/132559761/bb43d32e-05b6-4649-a953-c9ab20a976da)

**Comment by syr2212061031** [comment]
![J%0((YTF0C}%PQX55%8)SHE](https://github.com/umdreamer/leetcodeproblems/assets/132579828/81a11d1e-ed06-47d0-95a8-4d2f49fb4f7e)

**Comment by htywan** [comment]
![QQ截图20230509202506](https://github.com/umdreamer/leetcodeproblems/assets/132428178/0ba04a98-27a0-4b0d-90bc-19a5a33fb186)

**Comment by shylieisme** [comment]
![ZK23BWD 2EH}UWH@I@S UHE](https://github.com/umdreamer/leetcodeproblems/assets/132582721/edc08f6f-7e9c-499f-b7da-93927143f5fc)

**Comment by 123lrb** [comment]
![@6% 2HU6L4SU}_@$4A7TPKU](https://github.com/umdreamer/leetcodeproblems/assets/132526491/2c13387b-29d3-449f-9beb-022b2afdb20d)

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/6e2e7187-ff7e-446f-a7a9-ddd858a20939)

**Comment by 686xiaozhang** [comment]
![QQ截图20230509205143](https://github.com/umdreamer/leetcodeproblems/assets/132082348/b88c17af-46cb-433c-ab77-c9f68f66e4cf)

**Comment by gusuning** [comment]
<img width="616" alt="屏幕截图 2023-05-09 205452" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/6cd969fa-cf9c-483f-9ff7-88eed1605f17">

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/c10a5bc6-42a2-405d-9093-b5a1bd19e0fa)

**Comment by bedauern** [comment]
<img width="876" alt="Snipaste_2023-05-09_20-58-53" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/15fd5cc6-acf0-4b8e-ae14-be24585068a8">

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/4bb43089-0c47-435b-a5a8-7cfce550ad53)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-09 210750](https://github.com/umdreamer/leetcodeproblems/assets/117709686/3ae242ce-9dca-4c52-b7c5-c8f7c01f828f)

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/7a09c292-99e0-453c-a9ed-6fd767f6056b)

**Comment by huangyumei1** [comment]
![QQ截图20230509212111](https://github.com/umdreamer/leetcodeproblems/assets/122475924/1f7b2476-c4bf-4c2a-8033-b0dcba56f30c)

**Comment by qby962464** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132563315/98bdede3-2d16-4740-8d06-99861308dd58)

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/85cf93fb-b923-4825-a1e7-7dfa6fd3216e)

**Comment by 24zlx** [comment]
![联想截图_20230509224239](https://github.com/umdreamer/leetcodeproblems/assets/132560099/b336338f-29f5-422e-a408-8a8920db31b7)

**Comment by 12baoxingyu-6** [comment]
<img width="826" alt="屏幕截图 2023-05-09 230329" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/f0ab7de6-be01-4cb3-b28b-24641fc51aa4">

**Comment by FXL1006** [comment]
<img width="796" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/f197209d-2e59-42f5-b2db-f96d364eca11">

**Comment by cuixiao02** [comment]
<img width="1280" alt="截屏2023-05-10 17 57 43" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/f5e9eba0-1a7c-4dc3-98ae-4f4634d18161">
