### ISSUE TITLE
2023.5.10 Problem: 21. Merge Two Sorted Lists

### ISSUE THREAD

**Issue by umdreamer** [umdreamer/leetcodeproblems#9]
21. Merge Two Sorted Lists
[Problem Link](https://leetcode.cn/problems/merge-two-sorted-lists/)

You are given the heads of two sorted linked lists list1 and list2.

Merge the two lists in a one sorted list. The list should be made by splicing together the nodes of the first two lists.

Return the head of the merged linked list.

Example 1:

![image](https://github.com/umdreamer/leetcodeproblems/assets/15782682/6bf7338e-dbe5-4a62-8bec-4c3d8985104a)
```
Input: list1 = [1,2,4], list2 = [1,3,4]
Output: [1,1,2,3,4,4]
```
Example 2:
```
Input: list1 = [], list2 = []
Output: []
```
Example 3:
```
Input: list1 = [], list2 = [0]
Output: [0]
``` 

Constraints:

* The number of nodes in both lists is in the range [0, 50].
* -100 <= Node.val <= 100
* Both list1 and list2 are sorted in non-decreasing order.

**Comment by yeyuxq** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/128273789/361abcf6-d2a6-4be8-af52-d6cc829fee06)

**Comment by cuixiao02** [comment]
<img width="1280" alt="截屏2023-05-10 18 00 30" src="https://github.com/umdreamer/leetcodeproblems/assets/132454083/053e17dc-7d7d-4381-a2d0-7adb7de477d3">

**Comment by zyhzxy99** [comment]
![8WNRJ_WX4~IUH{U~~_SF6HJ](https://github.com/umdreamer/leetcodeproblems/assets/132050929/9c836231-ac01-496d-85ec-18dd608e9540)

**Comment by mafanjia** [comment]
![截屏6](https://github.com/umdreamer/leetcodeproblems/assets/132454776/034452f1-7211-4314-a5ba-a0025ad3a513)

**Comment by 1125766961** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132560784/d8f4480f-181c-425c-89d6-d50bf40471d0)

**Comment by ZWJ2212061008** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132138380/a6ee09ba-574f-44e1-a23c-bc53c971867e)

**Comment by promisewith7** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132559311/a060cf0f-eae3-49eb-9840-b175981d4b69)

**Comment by daowuwu** [comment]
![$JAK605E$6CJOO WOUE)BI0](https://github.com/umdreamer/leetcodeproblems/assets/132571490/10500195-45a7-4692-adb8-0797b61dc0fb)

**Comment by 12baoxingyu-6** [comment]
<img width="731" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132574617/1e026d4e-88b7-4c98-99fe-cc5f03679910">

**Comment by htywan** [comment]
![5](https://github.com/umdreamer/leetcodeproblems/assets/132428178/6140ba49-15c5-474f-b118-ffe5b2cd0614)

**Comment by liu-si-han** [comment]
<img width="823" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453391/c528f1f7-e185-4c74-9d84-f5e6d4cbf0b5">

**Comment by PinkyLame** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132571584/66292326-2601-4d54-a907-d19ca5ab76f7)

**Comment by gusuning** [comment]
<img width="899" alt="屏幕截图 2023-05-10 192718" src="https://github.com/umdreamer/leetcodeproblems/assets/126148849/10af0207-82e1-4095-8b78-e5b205a6ee2b">

**Comment by tangyexi** [comment]
<img width="848" alt="屏幕截图 2023-05-10 192813" src="https://github.com/umdreamer/leetcodeproblems/assets/132453549/ac224cc5-f5b9-487c-8d60-51bb67e3c587">

**Comment by xkqwww** [comment]
![36](https://github.com/umdreamer/leetcodeproblems/assets/132559761/2736b095-9005-4e19-a87f-9bd3f9ba6cd6)

**Comment by zhjingyan** [comment]
![Uploading image.png…]()

**Comment by zhjingyan** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132195009/08141f8c-320c-4a05-876e-0beff135a69a)

**Comment by liuhuanyu6** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132526191/8ea0e27f-4784-4f0b-b995-26db4c8506bb)

**Comment by sjh397** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132568283/e2f35d80-028a-44d5-8043-a20b37cfa5c1)

**Comment by Lggg1234** [comment]
![屏幕截图 2023-05-10 195558](https://github.com/umdreamer/leetcodeproblems/assets/117709686/bd74b25f-9f15-47c7-b966-805c8a5efa33)

**Comment by zangfushuo** [comment]
<img width="636" alt="截屏2023-05-10 19 42 45" src="https://github.com/umdreamer/leetcodeproblems/assets/132563136/e359ac4c-a0df-44d9-98b7-21b46e35148e">

**Comment by 123lrb** [comment]
![U%_N541L})TX$8W9WY@K%BL](https://github.com/umdreamer/leetcodeproblems/assets/132526491/90f9e9e7-49c6-4c9d-a048-26c205252456)

**Comment by naqianqpg** [comment]
![Q%JHCO@ALC@63W_52_OMM`T](https://github.com/umdreamer/leetcodeproblems/assets/132567187/3690f8bf-8692-4801-9634-139100cf6991)

**Comment by wangshiqi7** [comment]
<img width="1440" alt="截屏2023-05-10 20 28 13" src="https://github.com/umdreamer/leetcodeproblems/assets/132578339/11c71d7f-c6fc-41d5-83fd-7851e0499c70">

**Comment by foxbou** [comment]
<img width="1077" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132526020/c49392b3-6963-4e64-bda7-f31fdaeeb6d3">

**Comment by syr2212061031** [comment]
![I1YV8{(GAZM{LQ@KJK1~N)L](https://github.com/umdreamer/leetcodeproblems/assets/132579828/88efc4e4-ae8c-4d0f-93d0-371c133a4810)

**Comment by bedauern** [comment]
<img width="929" alt="Snipaste_2023-05-10_20-48-20" src="https://github.com/umdreamer/leetcodeproblems/assets/132483498/05e1e4fb-933e-4d74-8059-1313e4ffd6a2">

**Comment by 686xiaozhang** [comment]
![QQ截图20230510210729](https://github.com/umdreamer/leetcodeproblems/assets/132082348/826788c6-c3e1-4174-b4e3-a231759ebd4b)

**Comment by shylieisme** [comment]
![`NG3 9_C2A} 6T15E{}P TV](https://github.com/umdreamer/leetcodeproblems/assets/132582721/535c3d4f-7b18-4d99-941c-90970449592c)

**Comment by huangyumei1** [comment]
![QQ图片20230510215340](https://github.com/umdreamer/leetcodeproblems/assets/122475924/ab03d2d3-eeb1-4eb3-a1f0-44ea35041518)

**Comment by 24zlx** [comment]
![联想截图_20230510220108](https://github.com/umdreamer/leetcodeproblems/assets/132560099/1f3d3b72-3fe1-4b13-81b7-9e3acf680e34)

**Comment by FXL1006** [comment]
<img width="810" alt="image" src="https://github.com/umdreamer/leetcodeproblems/assets/132453630/4926cd61-7994-4709-abf1-b7ebf6a5cbf6">

**Comment by xiaolu2002** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132567090/82ecb348-5e51-4c1e-bb27-1e9c5465880a)

**Comment by zxm-1235** [comment]
![image](https://github.com/umdreamer/leetcodeproblems/assets/132538992/17533628-dc4d-48b8-8836-164ac77f1018)
